# Métodos Quantitativos
* Mestrado de Economia Aplicada


* Programa de Pós-Graduação em Economia (PPGE)


* Tema Economia da Saúde com o Título "Estado Nutricional em Alagoas segmentado para o sexo Masculino e Feminino (2008 - 2025)"


* **Alunos:** Adélia Lima, Alexandre Albuquerque e Beda Langou

Baixando as bibliotecas:



*   ! (Exclamação) - Comando para o terminal (prompt), detendo um classificação diferente de apenas um código comum de python. Nesse sentido, é importante ressaltar que em ambientes interativos online, tal sinal é obrigatório para baixar bilbiotecas de terceiros.


*   pip - gerenciador oficial do Python, sua função envolve buscar bibliotecas num repositório online e após isto baixá-la.

---
*   pandas - Usado para manipulação, limpeza e análise dos dados incluindo séries temporais, tabelas e outros componentes do ramo.


* statsmodels - módulo Python que fornece funções para a estimativa de modelos estatísticos, realização de testes estatísticos, e por fim exploração dados.


* scipy - Tal bibilioteca é derivada do módulo 'NumPy' fundamental para computação científica e matemática aplicada. Além disso, a mesma é dividida em diversos sub-bibliotecas e dado o foco estatístico do trabalho a principal se trata de scipy.stats, onde atua sobre distribuições de probabilidade, testes estatísticos e estatística descritiva.

In [1]:
!pip install pandas
!pip install statsmodels
!pip install scipy
!pip install matplotlib
!pip install seaborn
!pip install lxml

Requirement already satisfied: pandas in c:\users\desktop\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\desktop\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\desktop\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\desktop\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\desktop\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\desktop\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: statsmodels in c:\users\desktop\anaconda3\lib\site-packages (0.15.0)
Requirement already satisfied: numpy<3,>=1.23.5 in c:\users\desktop\anaconda3\lib\site-packages (from statsmodels) (2.1.3)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in c:\users\desktop\anaconda3\lib\site-packages (from statsmodels) (1.15.3)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\users\desktop\anaconda3\lib\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy>=0.5.6 in c:\users\desktop\anaconda3\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging>=21.3 in c:\users\desktop\anaconda3\lib\site-packages (from statsmodels) (24.2)
Requirement already satisfied: formulaic>=1.1.0 in c:\users\desktop\anaconda3\lib\site-packages (from statsmodels) (1.2.2)
Requirement already satisfied: interface-meta>=1.2.0 in c:\users\desktop\anaconda3\lib\site-packages (from formulaic>=1.1.0->statsmodels) (2.0.1)
Requirement already satisfied: narwhals>=1.17 in c:\users\desktop\anaconda3\lib\site-packages (from formulaic>=1.1.0->statsmodels) (1.31.0)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\desktop\anaconda3\lib\site-packages (from formulaic>=1.1.0->statsmodels) (4.12.2)
Requirement already satisfied: wrapt>=1.17.0rc1 in c:\users\desktop\anaconda3\lib\site-packages (from formulaic>=1.1.0->statsmodels) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\desktop\anaconda3\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\desktop\anaconda3\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\desktop\anaconda3\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\desktop\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Requirement already satisfied: scipy in c:\users\desktop\anaconda3\lib\site-packages (1.15.3)
Requirement already satisfied: numpy<2.5,>=1.23.5 in c:\users\desktop\anaconda3\lib\site-packages (from scipy) (2.1.3)
Requirement already satisfied: matplotlib in c:\users\desktop\anaconda3\lib\site-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\desktop\anaconda3\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\desktop\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\desktop\anaconda3\lib\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\desktop\anaconda3\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\desktop\anaconda3\lib\site-packages (from matplotlib) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\desktop\anaconda3\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\desktop\anaconda3\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\desktop\anaconda3\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\desktop\anaconda3\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\desktop\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in c:\users\desktop\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\desktop\anaconda3\lib\site-packages (from seaborn) (2.1.3)
Requirement already satisfied: pandas>=1.2 in c:\users\desktop\anaconda3\lib\site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\desktop\anaconda3\lib\site-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\desktop\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\desktop\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\desktop\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\desktop\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\desktop\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\desktop\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\desktop\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\desktop\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\desktop\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\desktop\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\desktop\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: lxml in c:\users\desktop\anaconda3\lib\site-packages (5.3.0)

Interligando o Google Drive ao ambiente do notebook do Google Colab:

*   from - Expressão que envolve "vindo de", nesse parte o que ocorre envolve um conjunto de ferramentas.


*   google.colab - Local específico que será retirada uma ferramenta necessária para atuação do código.



*   Import - Nesse cenário, selecionamos a ferramenta.



*   drive - Ferramenta exata buscada dentro do local.
---
* drive.mount () - Usado para conectar o seu Google Drive ao ambiente de execução

* /content/drive - é o diretório padrão no Colab, permitindo acesso transparente como se fossem arquivos locais.

In [2]:
# from google.colab import drive
# drive.mount('/content/drive')

Importando as bibliotecas a serem utilizadas:



*   Import - Concede acesso as funções do Python em pacotes externos



*   pandas - biblioteca voltada para manipulação e análise de dados. Em particular, opera sobre tabelas e séries temporais.


* as pd - Mandeira padrão e apreviado para pandas, em outras palavras, apelido da biblioteca.

In [3]:
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

Pergunta problema:
* Existem relação significativa entre o estado nutricional de mulheres e homens adultos entre os anos de 2008 até 2025 em Alagoas?
---

Objetivo geral:
* Verificar se no período analisado (2008 - 2025) houve correlação nos estados nutricionais entre os sexos masculinos e femininos no estado de Alagoas.
----

Objetivos específicos:

* Apresentar a estatística descritiva dos dados e aplicação dos testes (Mann Whithey U e Spearmarn) nas variavéis baixo peso, adequado, sobrepeso, obesidade de grau I, II e III no período entre 2008 e 2025 para homens e mulheres no Estado através da manipulação de tabelas e gráficos.

---

Hipóteses:

H0: Através do teste Mann-Wwhitney: Há diferenças entre o estado nutricional de mulheres e homens (Baixo Peso, Peso Adequado, Sobrepeso, Obsedidade Grau I, Obesidade Grau II e Obesidade Grau III) em Alagoas.

H1: Através do teste Mann-Wwhitney: Não há diferenças entre o estado nutricional de mulheres e homens (Baixo Peso, Peso Adequado, Sobrepeso, Obsedidade Grau I, Obesidade Grau II e Obesidade Grau III) em Alagoas.

----

H0: Através do teste Spearman: Há relação entre o estado nutricional de homens e mulheres (Baixo Peso, Peso Adequado, Sobrepeso, Obsedidade Grau I, Obesidade Grau II e Obesidade Grau III) em Alagoas.

H1: Através do teste Spearman: Não há relação entre o estado nutricional de homens e mulheres (Baixo Peso, Peso Adequado, Sobrepeso, Obsedidade Grau I, Obesidade Grau II e Obesidade Grau III)  em Alagoas.

* A justificativa da escolha das variáveis de interesse, das variáveis de comparação e das covariáveis consideradas relevantes para a investigação;


* A justificativa da escolha das variáveis de interesse

A priori é necessário compreender que o estudo se baseia na Economia da Saúde, ramo que aplica métodos econômicos ao setor de saúde, por meio da compreensão em torno da eficiência da alocação dos recursos e das variavéis correlacionadas ao bem-estar dos agentes econômicos. Mediante o exposto, a desregulação nos estados nutricionais tanto em casos de alta taxas de gorduras quanto no caso de baixo peso corporal, trazem sérios riscos à saúde, podendo reduzir o bem-estar e elevar os custos medicamentosos.


* Variáveis de comparação e das covariáveis

As variavéis escolhidas detém correlação com o estado nutricional dos indíviduos segmentados pelo recorte de adultos do sexo masculino e feminino entre 2008 - 2025, onde por meio das quantidades por ano estuda-se o nível de baixo peso, sobrepeso e obesidade dividada nos graus I, II e III.

Em suma, o desenvolvimento do trabalho será por meio do estado nutricional (unidade de análise) de mulheres e homens adultos (população de interesse) com baixo peso, peso adequado, sobrepeso, obesidade grau I, II e III (principais variáveis), durante o período de 2008 a 2025 (período), no Estado de Alagoas (cobertura geográfica).

Lendo a base com as informações do sexo masculino:




*   html_mas_2008 - Variável que retorna uma lista de DataFrames


*   = pd.read_html - função do pandas que procura todas as tabelas HTML contidas, resultando em uma lista (table encontrada no formato de HTML). A explicação sobre a determinação do formato dos arquivos envolvem a compreensão que apesar da extensão .xls, não se tratam de um Excel (2007), mas sim um documento HTML salvo com esta extensão. Sendo assim o read_html se faz necessário para a situação pertinente.




*   encoding='utf-8' - Simboliza Codificação UTF-8 (codificação de caracteres), sendo o padrão universal mais utilizado na web e em sistemas modernos. Nesse sentido, a padronização garante que caracteres acentuados e especiais sejam lidos corretamente



*   header=3 - Onde basicamente tratamos da lógica de índices, que iniciam em 0 e representam a 1º linha, em que a 4º (quarta) linha da tabela HTML será usada como nome das colunas.



*   thousands='.' - Adota a regra de ponto como separador de milhares. Ex: 1.500 retorna 1500


*   decimal=',' - Vírgula como separador decimal. Para o Python a tabela a conversão em float. Ex: 3,14 retorna 3.14 devido a leitura do sistema.

In [4]:
html_mas_2008 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Masculino_2008.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_mas_2009 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Masculino_2009.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_mas_2010 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Masculino_2010.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_mas_2011 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Masculino_2011.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_mas_2012 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Masculino_2012.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_mas_2013 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Masculino_2013.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_mas_2014 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Masculino_2014.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_mas_2015 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Masculino_2015.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_mas_2016 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Masculino_2016.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_mas_2017 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Masculino_2017.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_mas_2018 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Masculino_2018.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_mas_2019 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Masculino_2019.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_mas_2020 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Masculino_2020.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_mas_2021 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Masculino_2021.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_mas_2022 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Masculino_2022.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_mas_2023 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Masculino_2023.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_mas_2024 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Masculino_2024.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_mas_2025 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Masculino_2025.xls', encoding='utf-8', header=3, thousands='.', decimal=',')

html_mas_2025

[                   Região              Código UF                     UF  \
 0                NORDESTE                     27                     AL
 1                NORDESTE                     27                     AL
 2                NORDESTE                     27                     AL
 3                NORDESTE                     27                     AL
 4                NORDESTE                     27                     AL
 5                NORDESTE                     27                     AL
 6                NORDESTE                     27                     AL
 7                NORDESTE                     27                     AL
 8                NORDESTE                     27                     AL
 9                NORDESTE                     27                     AL
 10               NORDESTE                     27                     AL
 11  TOTAL REGIÃO NORDESTE  TOTAL REGIÃO NORDESTE  TOTAL REGIÃO NORDESTE
 12           TOTAL BRASIL           TOTAL BRASIL           TOTAL BRASIL

    Código da Região de Saúde        Região de Saúde   Total Unnamed: 6  \
 0                          2     2ª Região de Saúde     127      1.53%
 1                         44     1ª Região de Saúde    1173      2.45%
 2                         45     7ª Região de Saúde     711      2.15%
 3                         46     9ª Região de Saúde     301      1.82%
 4                        169     3ª Região de Saúde     251      2.06%
 5                        226    10ª Região de Saúde     205      1.83%
 6                        393     4ª Região de Saúde     117      1.49%
 7                        394     5ª Região de Saúde     242      1.72%
 8                        395     6ª Região de Saúde     200      1.33%
 9                        396     8ª Região de Saúde     164      1.98%
 10                        AL                     AL    3491         2%
 11     TOTAL REGIÃO NORDESTE  TOTAL REGIÃO NORDESTE   50178      2.12%
 12              TOTAL BRASIL           TOTAL BRASIL  179875      1.91%

     Unnamed: 7 Unnamed: 8  Unnamed: 9 Unnamed: 10  Unnamed: 11 Unnamed: 12  \
 0         2672     32.15%        3164      38.07%         1676      20.16%
 1        13958     29.19%       17535      36.66%        10222      21.37%
 2        11048     33.35%       12233      36.93%         6489      19.59%
 3         5747     34.78%        6279         38%         3050      18.46%
 4         3767     30.85%        4569      37.42%         2534      20.75%
 5         3825     34.19%        4246      37.95%         2117      18.92%
 6         2645     33.73%        2826      36.04%         1571      20.03%
 7         4071     28.85%        5305       37.6%         3079      21.82%
 8         4398     29.14%        5641      37.38%         3333      22.09%
 9         2795     33.72%        3105      37.45%         1618      19.52%
 10       54926     31.47%       64903      37.19%        35689      20.45%
 11      818473     34.51%      894273      37.71%       434981      18.34%
 12     2991194     31.84%     3475520         37%      1869507       19.9%

     Unnamed: 13 Unnamed: 14  Unnamed: 15 Unnamed: 16  Unnamed: 17
 0           470       5.65%          203       2.44%         8312
 1          3326       6.95%         1611       3.37%        47825
 2          1889        5.7%          754       2.28%        33124
 3           821       4.97%          326       1.97%        16524
 4           743       6.09%          346       2.83%        12210
 5           567       5.07%          227       2.03%        11187
 6           506       6.45%          177       2.26%         7842
 7          1015       7.19%          397       2.81%        14109
 8          1081       7.16%          438        2.9%        15091
 9           443       5.34%          165       1.99%         8290
 10        10861       6.22%         4644       2.66%       174514
 11       123231        5.2%        50444       2.13%      2371580
 12       598061       6.37%       280109       2.98%      9394266  ]

**Transformando** em dataframe/tabela:

*   Variável - df_mas_2008 que significa Tabela Masculino de 2008, nela está contida os dados da fonte oficial Sistema de Vigilância Alimentar e Nutricional (SISVAN)


*   pd - apelido do pandas que serve para transformar a variável


*   .DataFrame() - transformar em tabela/DataFrame.



*   (html_mas_2008[0]) - Variável que retorna uma lista pois estava no formato de HTML com extensão .xls, portanto representa a primeira tabela extraída do seu arquivo web original que foi lido pelo pandas

* ìndice [0] - Serve para contagem dos dados que inicia em 0 (zero).

* .head() - Em um DataFrame pandas retornas as primeiras linhas, na programação deteve a contagem (20), logo retornou 20 linhas do arquivo.

In [5]:
df_mas_2008 = pd.DataFrame(html_mas_2008[0])
df_mas_2009 = pd.DataFrame(html_mas_2009[0])
df_mas_2010 = pd.DataFrame(html_mas_2010[0])
df_mas_2011 = pd.DataFrame(html_mas_2011[0])
df_mas_2012 = pd.DataFrame(html_mas_2012[0])
df_mas_2013 = pd.DataFrame(html_mas_2013[0])
df_mas_2014 = pd.DataFrame(html_mas_2014[0])
df_mas_2015 = pd.DataFrame(html_mas_2015[0])
df_mas_2016 = pd.DataFrame(html_mas_2016[0])
df_mas_2017 = pd.DataFrame(html_mas_2017[0])
df_mas_2018 = pd.DataFrame(html_mas_2018[0])
df_mas_2019 = pd.DataFrame(html_mas_2019[0])
df_mas_2020 = pd.DataFrame(html_mas_2020[0])
df_mas_2021 = pd.DataFrame(html_mas_2021[0])
df_mas_2022 = pd.DataFrame(html_mas_2022[0])
df_mas_2023 = pd.DataFrame(html_mas_2023[0])
df_mas_2024 = pd.DataFrame(html_mas_2024[0])
df_mas_2025 = pd.DataFrame(html_mas_2025[0])
df_mas_2025.head(20) #so para ver como tinha ficado

,Região,Código UF,UF,Código da Região de Saúde,Região de Saúde,Total,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NORDESTE,27,AL,2,2ª Região de Saúde,127,1.53%,2672,32.15%,3164,38.07%,1676,20.16%,470,5.65%,203,2.44%,8312
1,NORDESTE,27,AL,44,1ª Região de Saúde,1173,2.45%,13958,29.19%,17535,36.66%,10222,21.37%,3326,6.95%,1611,3.37%,47825
2,NORDESTE,27,AL,45,7ª Região de Saúde,711,2.15%,11048,33.35%,12233,36.93%,6489,19.59%,1889,5.7%,754,2.28%,33124
3,NORDESTE,27,AL,46,9ª Região de Saúde,301,1.82%,5747,34.78%,6279,38%,3050,18.46%,821,4.97%,326,1.97%,16524
4,NORDESTE,27,AL,169,3ª Região de Saúde,251,2.06%,3767,30.85%,4569,37.42%,2534,20.75%,743,6.09%,346,2.83%,12210
5,NORDESTE,27,AL,226,10ª Região de Saúde,205,1.83%,3825,34.19%,4246,37.95%,2117,18.92%,567,5.07%,227,2.03%,11187
6,NORDESTE,27,AL,393,4ª Região de Saúde,117,1.49%,2645,33.73%,2826,36.04%,1571,20.03%,506,6.45%,177,2.26%,7842
7,NORDESTE,27,AL,394,5ª Região de Saúde,242,1.72%,4071,28.85%,5305,37.6%,3079,21.82%,1015,7.19%,397,2.81%,14109
8,NORDESTE,27,AL,395,6ª Região de Saúde,200,1.33%,4398,29.14%,5641,37.38%,3333,22.09%,1081,7.16%,438,2.9%,15091
9,NORDESTE,27,AL,396,8ª Região de Saúde,164,1.98%,2795,33.72%,3105,37.45%,1618,19.52%,443,5.34%,165,1.99%,8290
10,NORDESTE,27,AL,AL,AL,3491,2%,54926,31.47%,64903,37.19%,35689,20.45%,10861,6.22%,4644,2.66%,174514
11,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,50178,2.12%,818473,34.51%,894273,37.71%,434981,18.34%,123231,5.2%,50444,2.13%,2371580
12,TOTAL BRASIL,TOTAL BRASIL,TOTAL BRASIL,TOTAL BRASIL,TOTAL BRASIL,179875,1.91%,2991194,31.84%,3475520,37%,1869507,19.9%,598061,6.37%,280109,2.98%,9394266

Criando uma coluna de ano para cada dataframe:

- Em cada DataFrame foi adicionado a coluna 'Ano' atribuido a todas as linhas dessa coluna

- [] - cria coluna

- = atribui informação

In [6]:
df_mas_2008['Ano'] = 2008
df_mas_2009['Ano'] = 2009
df_mas_2010['Ano'] = 2010
df_mas_2011['Ano'] = 2011
df_mas_2012['Ano'] = 2012
df_mas_2013['Ano'] = 2013
df_mas_2014['Ano'] = 2014
df_mas_2015['Ano'] = 2015
df_mas_2016['Ano'] = 2016
df_mas_2017['Ano'] = 2017
df_mas_2018['Ano'] = 2018
df_mas_2019['Ano'] = 2019
df_mas_2020['Ano'] = 2020
df_mas_2021['Ano'] = 2021
df_mas_2022['Ano'] = 2022
df_mas_2023['Ano'] = 2023
df_mas_2024['Ano'] = 2024
df_mas_2025['Ano'] = 2025
df_mas_2025

,Região,Código UF,UF,Código da Região de Saúde,Região de Saúde,Total,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Ano
0,NORDESTE,27,AL,2,2ª Região de Saúde,127,1.53%,2672,32.15%,3164,38.07%,1676,20.16%,470,5.65%,203,2.44%,8312,2025
1,NORDESTE,27,AL,44,1ª Região de Saúde,1173,2.45%,13958,29.19%,17535,36.66%,10222,21.37%,3326,6.95%,1611,3.37%,47825,2025
2,NORDESTE,27,AL,45,7ª Região de Saúde,711,2.15%,11048,33.35%,12233,36.93%,6489,19.59%,1889,5.7%,754,2.28%,33124,2025
3,NORDESTE,27,AL,46,9ª Região de Saúde,301,1.82%,5747,34.78%,6279,38%,3050,18.46%,821,4.97%,326,1.97%,16524,2025
4,NORDESTE,27,AL,169,3ª Região de Saúde,251,2.06%,3767,30.85%,4569,37.42%,2534,20.75%,743,6.09%,346,2.83%,12210,2025
5,NORDESTE,27,AL,226,10ª Região de Saúde,205,1.83%,3825,34.19%,4246,37.95%,2117,18.92%,567,5.07%,227,2.03%,11187,2025
6,NORDESTE,27,AL,393,4ª Região de Saúde,117,1.49%,2645,33.73%,2826,36.04%,1571,20.03%,506,6.45%,177,2.26%,7842,2025
7,NORDESTE,27,AL,394,5ª Região de Saúde,242,1.72%,4071,28.85%,5305,37.6%,3079,21.82%,1015,7.19%,397,2.81%,14109,2025
8,NORDESTE,27,AL,395,6ª Região de Saúde,200,1.33%,4398,29.14%,5641,37.38%,3333,22.09%,1081,7.16%,438,2.9%,15091,2025
9,NORDESTE,27,AL,396,8ª Região de Saúde,164,1.98%,2795,33.72%,3105,37.45%,1618,19.52%,443,5.34%,165,1.99%,8290,2025
10,NORDESTE,27,AL,AL,AL,3491,2%,54926,31.47%,64903,37.19%,35689,20.45%,10861,6.22%,4644,2.66%,174514,2025
11,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,50178,2.12%,818473,34.51%,894273,37.71%,434981,18.34%,123231,5.2%,50444,2.13%,2371580,2025
12,TOTAL BRASIL,TOTAL BRASIL,TOTAL BRASIL,TOTAL BRASIL,TOTAL BRASIL,179875,1.91%,2991194,31.84%,3475520,37%,1869507,19.9%,598061,6.37%,280109,2.98%,9394266,2025

Selecionando as colunas a serem utilizadas:

- df_mas_2008_col_sel - Nova variável que irá retornar aspectos específicos dos DataFrames criados.

- = pd.DataFrame(...) - Retorna tabela

- df_mas_2008 - Tabela já retornada anteriormente que contém dados com respectivos anos atribuídos.

- , columns=[...] - columns é um dos argumentos (parâmetros) da estrutura pd.DataFrame(). Desse modo, selecionando colunas especificas.

A tabela anterior retornou colunas sem nome devido quebras e mesclagens então para organizar isto é necessário selecionar essas colunas, organizar e após renomear.

In [7]:
df_mas_2008_col_sel = pd.DataFrame(df_mas_2008, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_mas_2009_col_sel = pd.DataFrame(df_mas_2009, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_mas_2010_col_sel = pd.DataFrame(df_mas_2010, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_mas_2011_col_sel = pd.DataFrame(df_mas_2011, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_mas_2012_col_sel = pd.DataFrame(df_mas_2012, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_mas_2013_col_sel = pd.DataFrame(df_mas_2013, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_mas_2014_col_sel = pd.DataFrame(df_mas_2014, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_mas_2015_col_sel = pd.DataFrame(df_mas_2015, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_mas_2016_col_sel = pd.DataFrame(df_mas_2016, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_mas_2017_col_sel = pd.DataFrame(df_mas_2017, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_mas_2018_col_sel = pd.DataFrame(df_mas_2018, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_mas_2019_col_sel = pd.DataFrame(df_mas_2019, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_mas_2020_col_sel = pd.DataFrame(df_mas_2020, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_mas_2021_col_sel = pd.DataFrame(df_mas_2021, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_mas_2022_col_sel = pd.DataFrame(df_mas_2022, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_mas_2023_col_sel = pd.DataFrame(df_mas_2023, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_mas_2024_col_sel = pd.DataFrame(df_mas_2024, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_mas_2025_col_sel = pd.DataFrame(df_mas_2025, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_mas_2025_col_sel

,Ano,Código da Região de Saúde,Região de Saúde,Total,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,2025,2,2ª Região de Saúde,127,1.53%,2672,32.15%,3164,38.07%,1676,20.16%,470,5.65%,203,2.44%,8312
1,2025,44,1ª Região de Saúde,1173,2.45%,13958,29.19%,17535,36.66%,10222,21.37%,3326,6.95%,1611,3.37%,47825
2,2025,45,7ª Região de Saúde,711,2.15%,11048,33.35%,12233,36.93%,6489,19.59%,1889,5.7%,754,2.28%,33124
3,2025,46,9ª Região de Saúde,301,1.82%,5747,34.78%,6279,38%,3050,18.46%,821,4.97%,326,1.97%,16524
4,2025,169,3ª Região de Saúde,251,2.06%,3767,30.85%,4569,37.42%,2534,20.75%,743,6.09%,346,2.83%,12210
5,2025,226,10ª Região de Saúde,205,1.83%,3825,34.19%,4246,37.95%,2117,18.92%,567,5.07%,227,2.03%,11187
6,2025,393,4ª Região de Saúde,117,1.49%,2645,33.73%,2826,36.04%,1571,20.03%,506,6.45%,177,2.26%,7842
7,2025,394,5ª Região de Saúde,242,1.72%,4071,28.85%,5305,37.6%,3079,21.82%,1015,7.19%,397,2.81%,14109
8,2025,395,6ª Região de Saúde,200,1.33%,4398,29.14%,5641,37.38%,3333,22.09%,1081,7.16%,438,2.9%,15091
9,2025,396,8ª Região de Saúde,164,1.98%,2795,33.72%,3105,37.45%,1618,19.52%,443,5.34%,165,1.99%,8290
10,2025,AL,AL,3491,2%,54926,31.47%,64903,37.19%,35689,20.45%,10861,6.22%,4644,2.66%,174514
11,2025,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,50178,2.12%,818473,34.51%,894273,37.71%,434981,18.34%,123231,5.2%,50444,2.13%,2371580
12,2025,TOTAL BRASIL,TOTAL BRASIL,179875,1.91%,2991194,31.84%,3475520,37%,1869507,19.9%,598061,6.37%,280109,2.98%,9394266

Renomeando as colunas:
- ( ) - Como principal atributo serve para quando usar uma função, os argumentos irem dentro dos parênteses.

- [] - Serve como criador de listas, selecionador de indexadores e et al.

- { } - Usado para renomeador colunas. Na qual também é usado para Dicionários, sets, expressões em f-strings (nomes).

In [8]:
df_mas_2008_renomeado = pd.DataFrame.rename(df_mas_2008_col_sel, columns = {
    'Total':'Quantidade de homens com baixo peso',
    'Unnamed: 6': 'Percentual de homens baixo peso',
    'Unnamed: 7':'Quantidade de homens com peso adequado',
    'Unnamed: 8':'Percentual de homens com peso adequado',
    'Unnamed: 9':'Quantidade de homens com sobrepeso',
    'Unnamed: 10':'Percentual de homens com sobrepeso',
    'Unnamed: 11':'Quantidade de homens com obesidade grau I',
    'Unnamed: 12':'Percentual de homens com obesidade grau I',
    'Unnamed: 13':'Quantidade de homens com obesidade grau II',
    'Unnamed: 14':'Percentual de homens com obesidade grau II',
    'Unnamed: 15':'Quantidade de homens com obesidade grau III',
    'Unnamed: 16':'Percentual de homens com obesidade grau III',
    'Unnamed: 17':'Quantidade total de homens'
                                                                            })
df_mas_2009_renomeado = pd.DataFrame.rename(df_mas_2009_col_sel, columns = {
    'Total':'Quantidade de homens com baixo peso',
    'Unnamed: 6': 'Percentual de homens baixo peso',
    'Unnamed: 7':'Quantidade de homens com peso adequado',
    'Unnamed: 8':'Percentual de homens com peso adequado',
    'Unnamed: 9':'Quantidade de homens com sobrepeso',
    'Unnamed: 10':'Percentual de homens com sobrepeso',
    'Unnamed: 11':'Quantidade de homens com obesidade grau I',
    'Unnamed: 12':'Percentual de homens com obesidade grau I',
    'Unnamed: 13':'Quantidade de homens com obesidade grau II',
    'Unnamed: 14':'Percentual de homens com obesidade grau II',
    'Unnamed: 15':'Quantidade de homens com obesidade grau III',
    'Unnamed: 16':'Percentual de homens com obesidade grau III',
    'Unnamed: 17':'Quantidade total de homens'
                                                                            })
df_mas_2010_renomeado = pd.DataFrame.rename(df_mas_2010_col_sel, columns = {
    'Total':'Quantidade de homens com baixo peso',
    'Unnamed: 6': 'Percentual de homens baixo peso',
    'Unnamed: 7':'Quantidade de homens com peso adequado',
    'Unnamed: 8':'Percentual de homens com peso adequado',
    'Unnamed: 9':'Quantidade de homens com sobrepeso',
    'Unnamed: 10':'Percentual de homens com sobrepeso',
    'Unnamed: 11':'Quantidade de homens com obesidade grau I',
    'Unnamed: 12':'Percentual de homens com obesidade grau I',
    'Unnamed: 13':'Quantidade de homens com obesidade grau II',
    'Unnamed: 14':'Percentual de homens com obesidade grau II',
    'Unnamed: 15':'Quantidade de homens com obesidade grau III',
    'Unnamed: 16':'Percentual de homens com obesidade grau III',
    'Unnamed: 17':'Quantidade total de homens'
                                                                            })
df_mas_2011_renomeado = pd.DataFrame.rename(df_mas_2011_col_sel, columns = {
    'Total':'Quantidade de homens com baixo peso',
    'Unnamed: 6': 'Percentual de homens baixo peso',
    'Unnamed: 7':'Quantidade de homens com peso adequado',
    'Unnamed: 8':'Percentual de homens com peso adequado',
    'Unnamed: 9':'Quantidade de homens com sobrepeso',
    'Unnamed: 10':'Percentual de homens com sobrepeso',
    'Unnamed: 11':'Quantidade de homens com obesidade grau I',
    'Unnamed: 12':'Percentual de homens com obesidade grau I',
    'Unnamed: 13':'Quantidade de homens com obesidade grau II',
    'Unnamed: 14':'Percentual de homens com obesidade grau II',
    'Unnamed: 15':'Quantidade de homens com obesidade grau III',
    'Unnamed: 16':'Percentual de homens com obesidade grau III',
    'Unnamed: 17':'Quantidade total de homens'
                                                                            })
df_mas_2012_renomeado = pd.DataFrame.rename(df_mas_2012_col_sel, columns = {
    'Total':'Quantidade de homens com baixo peso',
    'Unnamed: 6': 'Percentual de homens baixo peso',
    'Unnamed: 7':'Quantidade de homens com peso adequado',
    'Unnamed: 8':'Percentual de homens com peso adequado',
    'Unnamed: 9':'Quantidade de homens com sobrepeso',
    'Unnamed: 10':'Percentual de homens com sobrepeso',
    'Unnamed: 11':'Quantidade de homens com obesidade grau I',
    'Unnamed: 12':'Percentual de homens com obesidade grau I',
    'Unnamed: 13':'Quantidade de homens com obesidade grau II',
    'Unnamed: 14':'Percentual de homens com obesidade grau II',
    'Unnamed: 15':'Quantidade de homens com obesidade grau III',
    'Unnamed: 16':'Percentual de homens com obesidade grau III',
    'Unnamed: 17':'Quantidade total de homens'
                                                                            })
df_mas_2013_renomeado = pd.DataFrame.rename(df_mas_2013_col_sel, columns = {
    'Total':'Quantidade de homens com baixo peso',
    'Unnamed: 6': 'Percentual de homens baixo peso',
    'Unnamed: 7':'Quantidade de homens com peso adequado',
    'Unnamed: 8':'Percentual de homens com peso adequado',
    'Unnamed: 9':'Quantidade de homens com sobrepeso',
    'Unnamed: 10':'Percentual de homens com sobrepeso',
    'Unnamed: 11':'Quantidade de homens com obesidade grau I',
    'Unnamed: 12':'Percentual de homens com obesidade grau I',
    'Unnamed: 13':'Quantidade de homens com obesidade grau II',
    'Unnamed: 14':'Percentual de homens com obesidade grau II',
    'Unnamed: 15':'Quantidade de homens com obesidade grau III',
    'Unnamed: 16':'Percentual de homens com obesidade grau III',
    'Unnamed: 17':'Quantidade total de homens'
                                                                            })
df_mas_2014_renomeado = pd.DataFrame.rename(df_mas_2014_col_sel, columns = {
    'Total':'Quantidade de homens com baixo peso',
    'Unnamed: 6': 'Percentual de homens baixo peso',
    'Unnamed: 7':'Quantidade de homens com peso adequado',
    'Unnamed: 8':'Percentual de homens com peso adequado',
    'Unnamed: 9':'Quantidade de homens com sobrepeso',
    'Unnamed: 10':'Percentual de homens com sobrepeso',
    'Unnamed: 11':'Quantidade de homens com obesidade grau I',
    'Unnamed: 12':'Percentual de homens com obesidade grau I',
    'Unnamed: 13':'Quantidade de homens com obesidade grau II',
    'Unnamed: 14':'Percentual de homens com obesidade grau II',
    'Unnamed: 15':'Quantidade de homens com obesidade grau III',
    'Unnamed: 16':'Percentual de homens com obesidade grau III',
    'Unnamed: 17':'Quantidade total de homens'
                                                                            })
df_mas_2015_renomeado = pd.DataFrame.rename(df_mas_2015_col_sel, columns = {
    'Total':'Quantidade de homens com baixo peso',
    'Unnamed: 6': 'Percentual de homens baixo peso',
    'Unnamed: 7':'Quantidade de homens com peso adequado',
    'Unnamed: 8':'Percentual de homens com peso adequado',
    'Unnamed: 9':'Quantidade de homens com sobrepeso',
    'Unnamed: 10':'Percentual de homens com sobrepeso',
    'Unnamed: 11':'Quantidade de homens com obesidade grau I',
    'Unnamed: 12':'Percentual de homens com obesidade grau I',
    'Unnamed: 13':'Quantidade de homens com obesidade grau II',
    'Unnamed: 14':'Percentual de homens com obesidade grau II',
    'Unnamed: 15':'Quantidade de homens com obesidade grau III',
    'Unnamed: 16':'Percentual de homens com obesidade grau III',
    'Unnamed: 17':'Quantidade total de homens'
                                                                            })
df_mas_2016_renomeado = pd.DataFrame.rename(df_mas_2016_col_sel, columns = {
    'Total':'Quantidade de homens com baixo peso',
    'Unnamed: 6': 'Percentual de homens baixo peso',
    'Unnamed: 7':'Quantidade de homens com peso adequado',
    'Unnamed: 8':'Percentual de homens com peso adequado',
    'Unnamed: 9':'Quantidade de homens com sobrepeso',
    'Unnamed: 10':'Percentual de homens com sobrepeso',
    'Unnamed: 11':'Quantidade de homens com obesidade grau I',
    'Unnamed: 12':'Percentual de homens com obesidade grau I',
    'Unnamed: 13':'Quantidade de homens com obesidade grau II',
    'Unnamed: 14':'Percentual de homens com obesidade grau II',
    'Unnamed: 15':'Quantidade de homens com obesidade grau III',
    'Unnamed: 16':'Percentual de homens com obesidade grau III',
    'Unnamed: 17':'Quantidade total de homens'
                                                                            })
df_mas_2017_renomeado = pd.DataFrame.rename(df_mas_2017_col_sel, columns = {
    'Total':'Quantidade de homens com baixo peso',
    'Unnamed: 6': 'Percentual de homens baixo peso',
    'Unnamed: 7':'Quantidade de homens com peso adequado',
    'Unnamed: 8':'Percentual de homens com peso adequado',
    'Unnamed: 9':'Quantidade de homens com sobrepeso',
    'Unnamed: 10':'Percentual de homens com sobrepeso',
    'Unnamed: 11':'Quantidade de homens com obesidade grau I',
    'Unnamed: 12':'Percentual de homens com obesidade grau I',
    'Unnamed: 13':'Quantidade de homens com obesidade grau II',
    'Unnamed: 14':'Percentual de homens com obesidade grau II',
    'Unnamed: 15':'Quantidade de homens com obesidade grau III',
    'Unnamed: 16':'Percentual de homens com obesidade grau III',
    'Unnamed: 17':'Quantidade total de homens'
                                                                            })
df_mas_2018_renomeado = pd.DataFrame.rename(df_mas_2018_col_sel, columns = {
    'Total':'Quantidade de homens com baixo peso',
    'Unnamed: 6': 'Percentual de homens baixo peso',
    'Unnamed: 7':'Quantidade de homens com peso adequado',
    'Unnamed: 8':'Percentual de homens com peso adequado',
    'Unnamed: 9':'Quantidade de homens com sobrepeso',
    'Unnamed: 10':'Percentual de homens com sobrepeso',
    'Unnamed: 11':'Quantidade de homens com obesidade grau I',
    'Unnamed: 12':'Percentual de homens com obesidade grau I',
    'Unnamed: 13':'Quantidade de homens com obesidade grau II',
    'Unnamed: 14':'Percentual de homens com obesidade grau II',
    'Unnamed: 15':'Quantidade de homens com obesidade grau III',
    'Unnamed: 16':'Percentual de homens com obesidade grau III',
    'Unnamed: 17':'Quantidade total de homens'
                                                                            })
df_mas_2019_renomeado = pd.DataFrame.rename(df_mas_2019_col_sel, columns = {
    'Total':'Quantidade de homens com baixo peso',
    'Unnamed: 6': 'Percentual de homens baixo peso',
    'Unnamed: 7':'Quantidade de homens com peso adequado',
    'Unnamed: 8':'Percentual de homens com peso adequado',
    'Unnamed: 9':'Quantidade de homens com sobrepeso',
    'Unnamed: 10':'Percentual de homens com sobrepeso',
    'Unnamed: 11':'Quantidade de homens com obesidade grau I',
    'Unnamed: 12':'Percentual de homens com obesidade grau I',
    'Unnamed: 13':'Quantidade de homens com obesidade grau II',
    'Unnamed: 14':'Percentual de homens com obesidade grau II',
    'Unnamed: 15':'Quantidade de homens com obesidade grau III',
    'Unnamed: 16':'Percentual de homens com obesidade grau III',
    'Unnamed: 17':'Quantidade total de homens'
                                                                            })
df_mas_2020_renomeado = pd.DataFrame.rename(df_mas_2020_col_sel, columns = {
    'Total':'Quantidade de homens com baixo peso',
    'Unnamed: 6': 'Percentual de homens baixo peso',
    'Unnamed: 7':'Quantidade de homens com peso adequado',
    'Unnamed: 8':'Percentual de homens com peso adequado',
    'Unnamed: 9':'Quantidade de homens com sobrepeso',
    'Unnamed: 10':'Percentual de homens com sobrepeso',
    'Unnamed: 11':'Quantidade de homens com obesidade grau I',
    'Unnamed: 12':'Percentual de homens com obesidade grau I',
    'Unnamed: 13':'Quantidade de homens com obesidade grau II',
    'Unnamed: 14':'Percentual de homens com obesidade grau II',
    'Unnamed: 15':'Quantidade de homens com obesidade grau III',
    'Unnamed: 16':'Percentual de homens com obesidade grau III',
    'Unnamed: 17':'Quantidade total de homens'
                                                                            })
df_mas_2021_renomeado = pd.DataFrame.rename(df_mas_2021_col_sel, columns = {
    'Total':'Quantidade de homens com baixo peso',
    'Unnamed: 6': 'Percentual de homens baixo peso',
    'Unnamed: 7':'Quantidade de homens com peso adequado',
    'Unnamed: 8':'Percentual de homens com peso adequado',
    'Unnamed: 9':'Quantidade de homens com sobrepeso',
    'Unnamed: 10':'Percentual de homens com sobrepeso',
    'Unnamed: 11':'Quantidade de homens com obesidade grau I',
    'Unnamed: 12':'Percentual de homens com obesidade grau I',
    'Unnamed: 13':'Quantidade de homens com obesidade grau II',
    'Unnamed: 14':'Percentual de homens com obesidade grau II',
    'Unnamed: 15':'Quantidade de homens com obesidade grau III',
    'Unnamed: 16':'Percentual de homens com obesidade grau III',
    'Unnamed: 17':'Quantidade total de homens'
                                                                            })
df_mas_2022_renomeado = pd.DataFrame.rename(df_mas_2022_col_sel, columns = {
    'Total':'Quantidade de homens com baixo peso',
    'Unnamed: 6': 'Percentual de homens baixo peso',
    'Unnamed: 7':'Quantidade de homens com peso adequado',
    'Unnamed: 8':'Percentual de homens com peso adequado',
    'Unnamed: 9':'Quantidade de homens com sobrepeso',
    'Unnamed: 10':'Percentual de homens com sobrepeso',
    'Unnamed: 11':'Quantidade de homens com obesidade grau I',
    'Unnamed: 12':'Percentual de homens com obesidade grau I',
    'Unnamed: 13':'Quantidade de homens com obesidade grau II',
    'Unnamed: 14':'Percentual de homens com obesidade grau II',
    'Unnamed: 15':'Quantidade de homens com obesidade grau III',
    'Unnamed: 16':'Percentual de homens com obesidade grau III',
    'Unnamed: 17':'Quantidade total de homens'
                                                                            })
df_mas_2023_renomeado = pd.DataFrame.rename(df_mas_2023_col_sel, columns = {
    'Total':'Quantidade de homens com baixo peso',
    'Unnamed: 6': 'Percentual de homens baixo peso',
    'Unnamed: 7':'Quantidade de homens com peso adequado',
    'Unnamed: 8':'Percentual de homens com peso adequado',
    'Unnamed: 9':'Quantidade de homens com sobrepeso',
    'Unnamed: 10':'Percentual de homens com sobrepeso',
    'Unnamed: 11':'Quantidade de homens com obesidade grau I',
    'Unnamed: 12':'Percentual de homens com obesidade grau I',
    'Unnamed: 13':'Quantidade de homens com obesidade grau II',
    'Unnamed: 14':'Percentual de homens com obesidade grau II',
    'Unnamed: 15':'Quantidade de homens com obesidade grau III',
    'Unnamed: 16':'Percentual de homens com obesidade grau III',
    'Unnamed: 17':'Quantidade total de homens'
                                                                            })
df_mas_2024_renomeado = pd.DataFrame.rename(df_mas_2024_col_sel, columns = {
    'Total':'Quantidade de homens com baixo peso',
    'Unnamed: 6': 'Percentual de homens baixo peso',
    'Unnamed: 7':'Quantidade de homens com peso adequado',
    'Unnamed: 8':'Percentual de homens com peso adequado',
    'Unnamed: 9':'Quantidade de homens com sobrepeso',
    'Unnamed: 10':'Percentual de homens com sobrepeso',
    'Unnamed: 11':'Quantidade de homens com obesidade grau I',
    'Unnamed: 12':'Percentual de homens com obesidade grau I',
    'Unnamed: 13':'Quantidade de homens com obesidade grau II',
    'Unnamed: 14':'Percentual de homens com obesidade grau II',
    'Unnamed: 15':'Quantidade de homens com obesidade grau III',
    'Unnamed: 16':'Percentual de homens com obesidade grau III',
    'Unnamed: 17':'Quantidade total de homens'
                                                                            })
df_mas_2025_renomeado = pd.DataFrame.rename(df_mas_2025_col_sel, columns = {
    'Total':'Quantidade de homens com baixo peso',
    'Unnamed: 6': 'Percentual de homens baixo peso',
    'Unnamed: 7':'Quantidade de homens com peso adequado',
    'Unnamed: 8':'Percentual de homens com peso adequado',
    'Unnamed: 9':'Quantidade de homens com sobrepeso',
    'Unnamed: 10':'Percentual de homens com sobrepeso',
    'Unnamed: 11':'Quantidade de homens com obesidade grau I',
    'Unnamed: 12':'Percentual de homens com obesidade grau I',
    'Unnamed: 13':'Quantidade de homens com obesidade grau II',
    'Unnamed: 14':'Percentual de homens com obesidade grau II',
    'Unnamed: 15':'Quantidade de homens com obesidade grau III',
    'Unnamed: 16':'Percentual de homens com obesidade grau III',
    'Unnamed: 17':'Quantidade total de homens'
                                                                            })
df_mas_2025_renomeado

,Ano,Código da Região de Saúde,Região de Saúde,Quantidade de homens com baixo peso,Percentual de homens baixo peso,Quantidade de homens com peso adequado,Percentual de homens com peso adequado,Quantidade de homens com sobrepeso,Percentual de homens com sobrepeso,Quantidade de homens com obesidade grau I,Percentual de homens com obesidade grau I,Quantidade de homens com obesidade grau II,Percentual de homens com obesidade grau II,Quantidade de homens com obesidade grau III,Percentual de homens com obesidade grau III,Quantidade total de homens
0,2025,2,2ª Região de Saúde,127,1.53%,2672,32.15%,3164,38.07%,1676,20.16%,470,5.65%,203,2.44%,8312
1,2025,44,1ª Região de Saúde,1173,2.45%,13958,29.19%,17535,36.66%,10222,21.37%,3326,6.95%,1611,3.37%,47825
2,2025,45,7ª Região de Saúde,711,2.15%,11048,33.35%,12233,36.93%,6489,19.59%,1889,5.7%,754,2.28%,33124
3,2025,46,9ª Região de Saúde,301,1.82%,5747,34.78%,6279,38%,3050,18.46%,821,4.97%,326,1.97%,16524
4,2025,169,3ª Região de Saúde,251,2.06%,3767,30.85%,4569,37.42%,2534,20.75%,743,6.09%,346,2.83%,12210
5,2025,226,10ª Região de Saúde,205,1.83%,3825,34.19%,4246,37.95%,2117,18.92%,567,5.07%,227,2.03%,11187
6,2025,393,4ª Região de Saúde,117,1.49%,2645,33.73%,2826,36.04%,1571,20.03%,506,6.45%,177,2.26%,7842
7,2025,394,5ª Região de Saúde,242,1.72%,4071,28.85%,5305,37.6%,3079,21.82%,1015,7.19%,397,2.81%,14109
8,2025,395,6ª Região de Saúde,200,1.33%,4398,29.14%,5641,37.38%,3333,22.09%,1081,7.16%,438,2.9%,15091
9,2025,396,8ª Região de Saúde,164,1.98%,2795,33.72%,3105,37.45%,1618,19.52%,443,5.34%,165,1.99%,8290
10,2025,AL,AL,3491,2%,54926,31.47%,64903,37.19%,35689,20.45%,10861,6.22%,4644,2.66%,174514
11,2025,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,50178,2.12%,818473,34.51%,894273,37.71%,434981,18.34%,123231,5.2%,50444,2.13%,2371580
12,2025,TOTAL BRASIL,TOTAL BRASIL,179875,1.91%,2991194,31.84%,3475520,37%,1869507,19.9%,598061,6.37%,280109,2.98%,9394266

Lendo as bases com informações do sexo feminino:

In [9]:
html_fem_2008 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2008.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2009 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2009.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2010 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2010.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2011 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2011.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2012 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2012.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2013 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2013.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2014 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2014.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2015 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2015.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2016 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2016.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2017 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2017.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2018 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2018.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2019 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2019.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2020 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2020.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2021 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2021.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2022 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2022.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2023 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2023.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2024 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2024.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2025 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2025.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2025#so para ver como vinha a estrutura

[                   Região              Código UF                     UF  \
 0                NORDESTE                     27                     AL
 1                NORDESTE                     27                     AL
 2                NORDESTE                     27                     AL
 3                NORDESTE                     27                     AL
 4                NORDESTE                     27                     AL
 5                NORDESTE                     27                     AL
 6                NORDESTE                     27                     AL
 7                NORDESTE                     27                     AL
 8                NORDESTE                     27                     AL
 9                NORDESTE                     27                     AL
 10               NORDESTE                     27                     AL
 11  TOTAL REGIÃO NORDESTE  TOTAL REGIÃO NORDESTE  TOTAL REGIÃO NORDESTE
 12           TOTAL BRASIL           TOTAL BRASIL           TOTAL BRASIL

    Código da Região de Saúde        Região de Saúde   Total Unnamed: 6  \
 0                          2     2ª Região de Saúde     496      1.95%
 1                         44     1ª Região de Saúde    2855      2.13%
 2                         45     7ª Região de Saúde    1755      2.02%
 3                         46     9ª Região de Saúde     883         2%
 4                        169     3ª Região de Saúde     598      1.82%
 5                        226    10ª Região de Saúde     618      1.97%
 6                        393     4ª Região de Saúde     388      1.84%
 7                        394     5ª Região de Saúde     689      1.86%
 8                        395     6ª Região de Saúde     694      1.85%
 9                        396     8ª Região de Saúde     539      2.25%
 10                        AL                     AL    9515         2%
 11     TOTAL REGIÃO NORDESTE  TOTAL REGIÃO NORDESTE  142992      1.96%
 12              TOTAL BRASIL           TOTAL BRASIL  396796      1.78%

     Unnamed: 7 Unnamed: 8  Unnamed: 9 Unnamed: 10  Unnamed: 11 Unnamed: 12  \
 0         5840     22.93%        8375      32.88%         6355      24.95%
 1        31087     23.19%       42982      32.07%        32805      24.47%
 2        21948     25.25%       29862      34.35%        20965      24.12%
 3        11518     26.15%       15374      34.91%        10305       23.4%
 4         7611     23.12%       10962       33.3%         8114      24.65%
 5         8533     27.23%       10913      34.82%         7142      22.79%
 6         4955     23.47%        7154      33.88%         5246      24.84%
 7         8202     22.08%       12180      32.79%         9321       25.1%
 8         8016     21.31%       12059      32.06%         9783      26.01%
 9         6187     25.77%        8306       34.6%         5562      23.17%
 10      113897        24%      158167      33.33%       115598      24.36%
 11     1923043     26.41%     2571337      35.31%      1660315       22.8%
 12     5676428     25.47%     7509377      33.69%      5140233      23.06%

     Unnamed: 13 Unnamed: 14  Unnamed: 15 Unnamed: 16  Unnamed: 17
 0          2954       11.6%         1449       5.69%        25469
 1         15783      11.78%         8523       6.36%       134035
 2          8435        9.7%         3966       4.56%        86931
 3          4111       9.33%         1849        4.2%        44040
 4          3722      11.31%         1909        5.8%        32916
 5          2838       9.06%         1296       4.14%        31340
 6          2248      10.65%         1124       5.32%        21115
 7          4352      11.72%         2397       6.45%        37141
 8          4564      12.13%         2499       6.64%        37615
 9          2281        9.5%         1129        4.7%        24004
 10        51288      10.81%        26141       5.51%       474606
 11       668429       9.18%       315540       4.33%      7281656
 12      2293482      10.29%      1271334        5.7%     22287650  ]

In [10]:
html_fem_2008 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2008.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2009 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2009.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2010 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2010.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2011 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2011.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2012 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2012.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2013 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2013.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2014 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2014.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2015 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2015.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2016 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2016.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2017 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2017.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2018 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2018.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2019 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2019.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2020 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2020.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2021 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2021.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2022 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2022.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2023 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2023.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2024 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2024.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2025 = pd.read_html(r'C:\Users\DESKTOP\Desktop\SCRIPT - OBESIDADE\Base\Feminino_2025.xls', encoding='utf-8', header=3, thousands='.', decimal=',')
html_fem_2025#so para ver como vinha a estrutura

[                   Região              Código UF                     UF  \
 0                NORDESTE                     27                     AL
 1                NORDESTE                     27                     AL
 2                NORDESTE                     27                     AL
 3                NORDESTE                     27                     AL
 4                NORDESTE                     27                     AL
 5                NORDESTE                     27                     AL
 6                NORDESTE                     27                     AL
 7                NORDESTE                     27                     AL
 8                NORDESTE                     27                     AL
 9                NORDESTE                     27                     AL
 10               NORDESTE                     27                     AL
 11  TOTAL REGIÃO NORDESTE  TOTAL REGIÃO NORDESTE  TOTAL REGIÃO NORDESTE
 12           TOTAL BRASIL           TOTAL BRASIL           TOTAL BRASIL

    Código da Região de Saúde        Região de Saúde   Total Unnamed: 6  \
 0                          2     2ª Região de Saúde     496      1.95%
 1                         44     1ª Região de Saúde    2855      2.13%
 2                         45     7ª Região de Saúde    1755      2.02%
 3                         46     9ª Região de Saúde     883         2%
 4                        169     3ª Região de Saúde     598      1.82%
 5                        226    10ª Região de Saúde     618      1.97%
 6                        393     4ª Região de Saúde     388      1.84%
 7                        394     5ª Região de Saúde     689      1.86%
 8                        395     6ª Região de Saúde     694      1.85%
 9                        396     8ª Região de Saúde     539      2.25%
 10                        AL                     AL    9515         2%
 11     TOTAL REGIÃO NORDESTE  TOTAL REGIÃO NORDESTE  142992      1.96%
 12              TOTAL BRASIL           TOTAL BRASIL  396796      1.78%

     Unnamed: 7 Unnamed: 8  Unnamed: 9 Unnamed: 10  Unnamed: 11 Unnamed: 12  \
 0         5840     22.93%        8375      32.88%         6355      24.95%
 1        31087     23.19%       42982      32.07%        32805      24.47%
 2        21948     25.25%       29862      34.35%        20965      24.12%
 3        11518     26.15%       15374      34.91%        10305       23.4%
 4         7611     23.12%       10962       33.3%         8114      24.65%
 5         8533     27.23%       10913      34.82%         7142      22.79%
 6         4955     23.47%        7154      33.88%         5246      24.84%
 7         8202     22.08%       12180      32.79%         9321       25.1%
 8         8016     21.31%       12059      32.06%         9783      26.01%
 9         6187     25.77%        8306       34.6%         5562      23.17%
 10      113897        24%      158167      33.33%       115598      24.36%
 11     1923043     26.41%     2571337      35.31%      1660315       22.8%
 12     5676428     25.47%     7509377      33.69%      5140233      23.06%

     Unnamed: 13 Unnamed: 14  Unnamed: 15 Unnamed: 16  Unnamed: 17
 0          2954       11.6%         1449       5.69%        25469
 1         15783      11.78%         8523       6.36%       134035
 2          8435        9.7%         3966       4.56%        86931
 3          4111       9.33%         1849        4.2%        44040
 4          3722      11.31%         1909        5.8%        32916
 5          2838       9.06%         1296       4.14%        31340
 6          2248      10.65%         1124       5.32%        21115
 7          4352      11.72%         2397       6.45%        37141
 8          4564      12.13%         2499       6.64%        37615
 9          2281        9.5%         1129        4.7%        24004
 10        51288      10.81%        26141       5.51%       474606
 11       668429       9.18%       315540       4.33%      7281656
 12      2293482      10.29%      1271334        5.7%     22287650  ]

**Transformando** em dataframe

In [11]:
df_fem_2008 = pd.DataFrame(html_fem_2008[0])
df_fem_2009 = pd.DataFrame(html_fem_2009[0])
df_fem_2010 = pd.DataFrame(html_fem_2010[0])
df_fem_2011 = pd.DataFrame(html_fem_2011[0])
df_fem_2012 = pd.DataFrame(html_fem_2012[0])
df_fem_2013 = pd.DataFrame(html_fem_2013[0])
df_fem_2014 = pd.DataFrame(html_fem_2014[0])
df_fem_2015 = pd.DataFrame(html_fem_2015[0])
df_fem_2016 = pd.DataFrame(html_fem_2016[0])
df_fem_2017 = pd.DataFrame(html_fem_2017[0])
df_fem_2018 = pd.DataFrame(html_fem_2018[0])
df_fem_2019 = pd.DataFrame(html_fem_2019[0])
df_fem_2020 = pd.DataFrame(html_fem_2020[0])
df_fem_2021 = pd.DataFrame(html_fem_2021[0])
df_fem_2022 = pd.DataFrame(html_fem_2022[0])
df_fem_2023 = pd.DataFrame(html_fem_2023[0])
df_fem_2024 = pd.DataFrame(html_fem_2024[0])
df_fem_2025 = pd.DataFrame(html_fem_2025[0])
df_fem_2015.head(20) #so para ver como tinha ficado

,Região,Código UF,UF,Código da Região de Saúde,Região de Saúde,Total,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NORDESTE,27,AL,2,2ª Região de Saúde,528,2.5%,8425,39.89%,6962,32.96%,3545,16.78%,1190,5.63%,471,2.23%,21121
1,NORDESTE,27,AL,44,1ª Região de Saúde,578,2.71%,7439,34.92%,7435,34.9%,3902,18.32%,1357,6.37%,590,2.77%,21301
2,NORDESTE,27,AL,45,7ª Região de Saúde,1733,2.79%,24578,39.51%,21710,34.9%,10002,16.08%,3183,5.12%,1005,1.62%,62211
3,NORDESTE,27,AL,46,9ª Região de Saúde,954,2.94%,13021,40.16%,11518,35.53%,4998,15.42%,1425,4.4%,505,1.56%,32421
4,NORDESTE,27,AL,169,3ª Região de Saúde,659,2.64%,10073,40.38%,8355,33.49%,4069,16.31%,1321,5.3%,471,1.89%,24948
5,NORDESTE,27,AL,226,10ª Região de Saúde,551,2.73%,7847,38.89%,7128,35.33%,3255,16.13%,1026,5.08%,370,1.83%,20177
6,NORDESTE,27,AL,393,4ª Região de Saúde,477,2.99%,6011,37.66%,5543,34.73%,2678,16.78%,907,5.68%,345,2.16%,15961
7,NORDESTE,27,AL,394,5ª Região de Saúde,736,2.52%,10001,34.28%,10087,34.58%,5571,19.1%,1960,6.72%,816,2.8%,29171
8,NORDESTE,27,AL,395,6ª Região de Saúde,527,2.58%,6959,34.05%,7029,34.4%,4004,19.59%,1359,6.65%,557,2.73%,20435
9,NORDESTE,27,AL,396,8ª Região de Saúde,545,2.66%,8467,41.28%,7150,34.86%,3067,14.95%,944,4.6%,340,1.66%,20513
10,NORDESTE,27,AL,AL,AL,7288,2.72%,102821,38.33%,92917,34.64%,45091,16.81%,14672,5.47%,5470,2.04%,268259
11,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,152258,2.95%,2123500,41.17%,1782087,34.55%,785531,15.23%,234382,4.54%,79915,1.55%,5157673
12,TOTAL BRASIL,TOTAL BRASIL,TOTAL BRASIL,TOTAL BRASIL,TOTAL BRASIL,295040,2.8%,4084261,38.75%,3564181,33.82%,1736543,16.48%,597893,5.67%,261539,2.48%,10539457

Criando uma coluna de ano para cada dataframe:

In [12]:
df_fem_2008['Ano'] = 2008
df_fem_2009['Ano'] = 2009
df_fem_2010['Ano'] = 2010
df_fem_2011['Ano'] = 2011
df_fem_2012['Ano'] = 2012
df_fem_2013['Ano'] = 2013
df_fem_2014['Ano'] = 2014
df_fem_2015['Ano'] = 2015
df_fem_2016['Ano'] = 2016
df_fem_2017['Ano'] = 2017
df_fem_2018['Ano'] = 2018
df_fem_2019['Ano'] = 2019
df_fem_2020['Ano'] = 2020
df_fem_2021['Ano'] = 2021
df_fem_2022['Ano'] = 2022
df_fem_2023['Ano'] = 2023
df_fem_2024['Ano'] = 2024
df_fem_2025['Ano'] = 2025
df_fem_2008

,Região,Código UF,UF,Código da Região de Saúde,Região de Saúde,Total,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Ano
0,NORDESTE,27,AL,2,2ª Região de Saúde,468,4.59%,5005,49.04%,2953,28.94%,1264,12.39%,370,3.63%,145,1.42%,10205,2008
1,NORDESTE,27,AL,44,1ª Região de Saúde,557,4.97%,5306,47.38%,3513,31.37%,1310,11.7%,372,3.32%,141,1.26%,11199,2008
2,NORDESTE,27,AL,45,7ª Região de Saúde,2623,8.28%,15266,48.18%,10170,32.1%,2702,8.53%,673,2.12%,249,0.79%,31683,2008
3,NORDESTE,27,AL,46,9ª Região de Saúde,1567,7.4%,11475,54.16%,5765,27.21%,1788,8.44%,455,2.15%,138,0.65%,21188,2008
4,NORDESTE,27,AL,169,3ª Região de Saúde,2005,10.66%,9507,50.52%,4965,26.39%,1771,9.41%,425,2.26%,144,0.77%,18817,2008
5,NORDESTE,27,AL,226,10ª Região de Saúde,824,6.55%,6963,55.32%,3430,27.25%,1010,8.02%,254,2.02%,105,0.83%,12586,2008
6,NORDESTE,27,AL,393,4ª Região de Saúde,508,4.59%,6538,59.03%,2983,26.93%,799,7.21%,166,1.5%,82,0.74%,11076,2008
7,NORDESTE,27,AL,394,5ª Região de Saúde,1735,13.21%,5690,43.34%,3599,27.41%,1508,11.49%,443,3.37%,155,1.18%,13130,2008
8,NORDESTE,27,AL,395,6ª Região de Saúde,648,5.43%,5876,49.25%,3537,29.65%,1319,11.06%,391,3.28%,159,1.33%,11930,2008
9,NORDESTE,27,AL,396,8ª Região de Saúde,830,6.98%,6035,50.74%,3480,29.26%,1130,9.5%,310,2.61%,109,0.92%,11894,2008
10,NORDESTE,27,AL,AL,AL,11765,7.65%,77661,50.53%,44395,28.88%,14601,9.5%,3859,2.51%,1427,0.93%,153708,2008
11,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,173447,6.44%,1463592,54.36%,744100,27.64%,232553,8.64%,57978,2.15%,20666,0.77%,2692336,2008
12,TOTAL BRASIL,TOTAL BRASIL,TOTAL BRASIL,TOTAL BRASIL,TOTAL BRASIL,298609,5.78%,2655970,51.43%,1462587,28.32%,526146,10.19%,156355,3.03%,64856,1.26%,5164523,2008

Selecionando as colunas a serem utilizadas:

In [13]:
df_fem_2008_col_sel = pd.DataFrame(df_fem_2008, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_fem_2009_col_sel = pd.DataFrame(df_fem_2009, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_fem_2010_col_sel = pd.DataFrame(df_fem_2010, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_fem_2011_col_sel = pd.DataFrame(df_fem_2011, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_fem_2012_col_sel = pd.DataFrame(df_fem_2012, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_fem_2013_col_sel = pd.DataFrame(df_fem_2013, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_fem_2014_col_sel = pd.DataFrame(df_fem_2014, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_fem_2015_col_sel = pd.DataFrame(df_fem_2015, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_fem_2016_col_sel = pd.DataFrame(df_fem_2016, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_fem_2017_col_sel = pd.DataFrame(df_fem_2017, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_fem_2018_col_sel = pd.DataFrame(df_fem_2018, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_fem_2019_col_sel = pd.DataFrame(df_fem_2019, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_fem_2020_col_sel = pd.DataFrame(df_fem_2020, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_fem_2021_col_sel = pd.DataFrame(df_fem_2021, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_fem_2022_col_sel = pd.DataFrame(df_fem_2022, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_fem_2023_col_sel = pd.DataFrame(df_fem_2023, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_fem_2024_col_sel = pd.DataFrame(df_fem_2024, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_fem_2025_col_sel = pd.DataFrame(df_fem_2025, columns=['Ano','Código da Região de Saúde', 'Região de Saúde', 'Total', 'Unnamed: 6', 'Unnamed: 7','Unnamed: 8','Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14','Unnamed: 15','Unnamed: 16', 'Unnamed: 17'])
df_fem_2008_col_sel

,Ano,Código da Região de Saúde,Região de Saúde,Total,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,2008,2,2ª Região de Saúde,468,4.59%,5005,49.04%,2953,28.94%,1264,12.39%,370,3.63%,145,1.42%,10205
1,2008,44,1ª Região de Saúde,557,4.97%,5306,47.38%,3513,31.37%,1310,11.7%,372,3.32%,141,1.26%,11199
2,2008,45,7ª Região de Saúde,2623,8.28%,15266,48.18%,10170,32.1%,2702,8.53%,673,2.12%,249,0.79%,31683
3,2008,46,9ª Região de Saúde,1567,7.4%,11475,54.16%,5765,27.21%,1788,8.44%,455,2.15%,138,0.65%,21188
4,2008,169,3ª Região de Saúde,2005,10.66%,9507,50.52%,4965,26.39%,1771,9.41%,425,2.26%,144,0.77%,18817
5,2008,226,10ª Região de Saúde,824,6.55%,6963,55.32%,3430,27.25%,1010,8.02%,254,2.02%,105,0.83%,12586
6,2008,393,4ª Região de Saúde,508,4.59%,6538,59.03%,2983,26.93%,799,7.21%,166,1.5%,82,0.74%,11076
7,2008,394,5ª Região de Saúde,1735,13.21%,5690,43.34%,3599,27.41%,1508,11.49%,443,3.37%,155,1.18%,13130
8,2008,395,6ª Região de Saúde,648,5.43%,5876,49.25%,3537,29.65%,1319,11.06%,391,3.28%,159,1.33%,11930
9,2008,396,8ª Região de Saúde,830,6.98%,6035,50.74%,3480,29.26%,1130,9.5%,310,2.61%,109,0.92%,11894
10,2008,AL,AL,11765,7.65%,77661,50.53%,44395,28.88%,14601,9.5%,3859,2.51%,1427,0.93%,153708
11,2008,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,173447,6.44%,1463592,54.36%,744100,27.64%,232553,8.64%,57978,2.15%,20666,0.77%,2692336
12,2008,TOTAL BRASIL,TOTAL BRASIL,298609,5.78%,2655970,51.43%,1462587,28.32%,526146,10.19%,156355,3.03%,64856,1.26%,5164523

Renomeando as colunas que estao com 'unamed' dos dataframes:

In [14]:
df_fem_2008_renomeado = pd.DataFrame.rename(df_fem_2008_col_sel, columns = {
    'Total':'Quantidade de mulheres com baixo peso',
    'Unnamed: 6': 'Percentual de mulheres baixo peso',
    'Unnamed: 7':'Quantidade de mulheres com peso adequado',
    'Unnamed: 8':'Percentual de mulheres com peso adequado',
    'Unnamed: 9':'Quantidade de mulheres com sobrepeso',
    'Unnamed: 10':'Percentual de mulheres com sobrepeso',
    'Unnamed: 11':'Quantidade de mulheres com obesidade grau I',
    'Unnamed: 12':'Percentual de mulheres com obesidade grau I',
    'Unnamed: 13':'Quantidade de mulheres com obesidade grau II',
    'Unnamed: 14':'Percentual de mulheres com obesidade grau II',
    'Unnamed: 15':'Quantidade de mulheres com obesidade grau III',
    'Unnamed: 16':'Percentual de mulheres com obesidade grau III',
    'Unnamed: 17':'Quantidade total de mulheres'
                                                                            })
df_fem_2009_renomeado = pd.DataFrame.rename(df_fem_2009_col_sel, columns = {
    'Total':'Quantidade de mulheres com baixo peso',
    'Unnamed: 6': 'Percentual de mulheres baixo peso',
    'Unnamed: 7':'Quantidade de mulheres com peso adequado',
    'Unnamed: 8':'Percentual de mulheres com peso adequado',
    'Unnamed: 9':'Quantidade de mulheres com sobrepeso',
    'Unnamed: 10':'Percentual de mulheres com sobrepeso',
    'Unnamed: 11':'Quantidade de mulheres com obesidade grau I',
    'Unnamed: 12':'Percentual de mulheres com obesidade grau I',
    'Unnamed: 13':'Quantidade de mulheres com obesidade grau II',
    'Unnamed: 14':'Percentual de mulheres com obesidade grau II',
    'Unnamed: 15':'Quantidade de mulheres com obesidade grau III',
    'Unnamed: 16':'Percentual de mulheres com obesidade grau III',
    'Unnamed: 17':'Quantidade total de mulheres'
                                                                            })
df_fem_2010_renomeado = pd.DataFrame.rename(df_fem_2010_col_sel, columns = {
    'Total':'Quantidade de mulheres com baixo peso',
    'Unnamed: 6': 'Percentual de mulheres baixo peso',
    'Unnamed: 7':'Quantidade de mulheres com peso adequado',
    'Unnamed: 8':'Percentual de mulheres com peso adequado',
    'Unnamed: 9':'Quantidade de mulheres com sobrepeso',
    'Unnamed: 10':'Percentual de mulheres com sobrepeso',
    'Unnamed: 11':'Quantidade de mulheres com obesidade grau I',
    'Unnamed: 12':'Percentual de mulheres com obesidade grau I',
    'Unnamed: 13':'Quantidade de mulheres com obesidade grau II',
    'Unnamed: 14':'Percentual de mulheres com obesidade grau II',
    'Unnamed: 15':'Quantidade de mulheres com obesidade grau III',
    'Unnamed: 16':'Percentual de mulheres com obesidade grau III',
    'Unnamed: 17':'Quantidade total de mulheres'
                                                                            })
df_fem_2011_renomeado = pd.DataFrame.rename(df_fem_2011_col_sel, columns = {
    'Total':'Quantidade de mulheres com baixo peso',
    'Unnamed: 6': 'Percentual de mulheres baixo peso',
    'Unnamed: 7':'Quantidade de mulheres com peso adequado',
    'Unnamed: 8':'Percentual de mulheres com peso adequado',
    'Unnamed: 9':'Quantidade de mulheres com sobrepeso',
    'Unnamed: 10':'Percentual de mulheres com sobrepeso',
    'Unnamed: 11':'Quantidade de mulheres com obesidade grau I',
    'Unnamed: 12':'Percentual de mulheres com obesidade grau I',
    'Unnamed: 13':'Quantidade de mulheres com obesidade grau II',
    'Unnamed: 14':'Percentual de mulheres com obesidade grau II',
    'Unnamed: 15':'Quantidade de mulheres com obesidade grau III',
    'Unnamed: 16':'Percentual de mulheres com obesidade grau III',
    'Unnamed: 17':'Quantidade total de mulheres'
                                                                            })
df_fem_2012_renomeado = pd.DataFrame.rename(df_fem_2012_col_sel, columns = {
    'Total':'Quantidade de mulheres com baixo peso',
    'Unnamed: 6': 'Percentual de mulheres baixo peso',
    'Unnamed: 7':'Quantidade de mulheres com peso adequado',
    'Unnamed: 8':'Percentual de mulheres com peso adequado',
    'Unnamed: 9':'Quantidade de mulheres com sobrepeso',
    'Unnamed: 10':'Percentual de mulheres com sobrepeso',
    'Unnamed: 11':'Quantidade de mulheres com obesidade grau I',
    'Unnamed: 12':'Percentual de mulheres com obesidade grau I',
    'Unnamed: 13':'Quantidade de mulheres com obesidade grau II',
    'Unnamed: 14':'Percentual de mulheres com obesidade grau II',
    'Unnamed: 15':'Quantidade de mulheres com obesidade grau III',
    'Unnamed: 16':'Percentual de mulheres com obesidade grau III',
    'Unnamed: 17':'Quantidade total de mulheres'
                                                                            })
df_fem_2013_renomeado = pd.DataFrame.rename(df_fem_2013_col_sel, columns = {
    'Total':'Quantidade de mulheres com baixo peso',
    'Unnamed: 6': 'Percentual de mulheres baixo peso',
    'Unnamed: 7':'Quantidade de mulheres com peso adequado',
    'Unnamed: 8':'Percentual de mulheres com peso adequado',
    'Unnamed: 9':'Quantidade de mulheres com sobrepeso',
    'Unnamed: 10':'Percentual de mulheres com sobrepeso',
    'Unnamed: 11':'Quantidade de mulheres com obesidade grau I',
    'Unnamed: 12':'Percentual de mulheres com obesidade grau I',
    'Unnamed: 13':'Quantidade de mulheres com obesidade grau II',
    'Unnamed: 14':'Percentual de mulheres com obesidade grau II',
    'Unnamed: 15':'Quantidade de mulheres com obesidade grau III',
    'Unnamed: 16':'Percentual de mulheres com obesidade grau III',
    'Unnamed: 17':'Quantidade total de mulheres'
                                                                            })
df_fem_2014_renomeado = pd.DataFrame.rename(df_fem_2014_col_sel, columns = {
    'Total':'Quantidade de mulheres com baixo peso',
    'Unnamed: 6': 'Percentual de mulheres baixo peso',
    'Unnamed: 7':'Quantidade de mulheres com peso adequado',
    'Unnamed: 8':'Percentual de mulheres com peso adequado',
    'Unnamed: 9':'Quantidade de mulheres com sobrepeso',
    'Unnamed: 10':'Percentual de mulheres com sobrepeso',
    'Unnamed: 11':'Quantidade de mulheres com obesidade grau I',
    'Unnamed: 12':'Percentual de mulheres com obesidade grau I',
    'Unnamed: 13':'Quantidade de mulheres com obesidade grau II',
    'Unnamed: 14':'Percentual de mulheres com obesidade grau II',
    'Unnamed: 15':'Quantidade de mulheres com obesidade grau III',
    'Unnamed: 16':'Percentual de mulheres com obesidade grau III',
    'Unnamed: 17':'Quantidade total de mulheres'
                                                                            })
df_fem_2015_renomeado = pd.DataFrame.rename(df_fem_2015_col_sel, columns = {
    'Total':'Quantidade de mulheres com baixo peso',
    'Unnamed: 6': 'Percentual de mulheres baixo peso',
    'Unnamed: 7':'Quantidade de mulheres com peso adequado',
    'Unnamed: 8':'Percentual de mulheres com peso adequado',
    'Unnamed: 9':'Quantidade de mulheres com sobrepeso',
    'Unnamed: 10':'Percentual de mulheres com sobrepeso',
    'Unnamed: 11':'Quantidade de mulheres com obesidade grau I',
    'Unnamed: 12':'Percentual de mulheres com obesidade grau I',
    'Unnamed: 13':'Quantidade de mulheres com obesidade grau II',
    'Unnamed: 14':'Percentual de mulheres com obesidade grau II',
    'Unnamed: 15':'Quantidade de mulheres com obesidade grau III',
    'Unnamed: 16':'Percentual de mulheres com obesidade grau III',
    'Unnamed: 17':'Quantidade total de mulheres'
                                                                            })
df_fem_2016_renomeado = pd.DataFrame.rename(df_fem_2016_col_sel, columns = {
    'Total':'Quantidade de mulheres com baixo peso',
    'Unnamed: 6': 'Percentual de mulheres baixo peso',
    'Unnamed: 7':'Quantidade de mulheres com peso adequado',
    'Unnamed: 8':'Percentual de mulheres com peso adequado',
    'Unnamed: 9':'Quantidade de mulheres com sobrepeso',
    'Unnamed: 10':'Percentual de mulheres com sobrepeso',
    'Unnamed: 11':'Quantidade de mulheres com obesidade grau I',
    'Unnamed: 12':'Percentual de mulheres com obesidade grau I',
    'Unnamed: 13':'Quantidade de mulheres com obesidade grau II',
    'Unnamed: 14':'Percentual de mulheres com obesidade grau II',
    'Unnamed: 15':'Quantidade de mulheres com obesidade grau III',
    'Unnamed: 16':'Percentual de mulheres com obesidade grau III',
    'Unnamed: 17':'Quantidade total de mulheres'
                                                                            })
df_fem_2017_renomeado = pd.DataFrame.rename(df_fem_2017_col_sel, columns = {
    'Total':'Quantidade de mulheres com baixo peso',
    'Unnamed: 6': 'Percentual de mulheres baixo peso',
    'Unnamed: 7':'Quantidade de mulheres com peso adequado',
    'Unnamed: 8':'Percentual de mulheres com peso adequado',
    'Unnamed: 9':'Quantidade de mulheres com sobrepeso',
    'Unnamed: 10':'Percentual de mulheres com sobrepeso',
    'Unnamed: 11':'Quantidade de mulheres com obesidade grau I',
    'Unnamed: 12':'Percentual de mulheres com obesidade grau I',
    'Unnamed: 13':'Quantidade de mulheres com obesidade grau II',
    'Unnamed: 14':'Percentual de mulheres com obesidade grau II',
    'Unnamed: 15':'Quantidade de mulheres com obesidade grau III',
    'Unnamed: 16':'Percentual de mulheres com obesidade grau III',
    'Unnamed: 17':'Quantidade total de mulheres'
                                                                            })
df_fem_2018_renomeado = pd.DataFrame.rename(df_fem_2018_col_sel, columns = {
    'Total':'Quantidade de mulheres com baixo peso',
    'Unnamed: 6': 'Percentual de mulheres baixo peso',
    'Unnamed: 7':'Quantidade de mulheres com peso adequado',
    'Unnamed: 8':'Percentual de mulheres com peso adequado',
    'Unnamed: 9':'Quantidade de mulheres com sobrepeso',
    'Unnamed: 10':'Percentual de mulheres com sobrepeso',
    'Unnamed: 11':'Quantidade de mulheres com obesidade grau I',
    'Unnamed: 12':'Percentual de mulheres com obesidade grau I',
    'Unnamed: 13':'Quantidade de mulheres com obesidade grau II',
    'Unnamed: 14':'Percentual de mulheres com obesidade grau II',
    'Unnamed: 15':'Quantidade de mulheres com obesidade grau III',
    'Unnamed: 16':'Percentual de mulheres com obesidade grau III',
    'Unnamed: 17':'Quantidade total de mulheres'
                                                                            })
df_fem_2019_renomeado = pd.DataFrame.rename(df_fem_2019_col_sel, columns = {
    'Total':'Quantidade de mulheres com baixo peso',
    'Unnamed: 6': 'Percentual de mulheres baixo peso',
    'Unnamed: 7':'Quantidade de mulheres com peso adequado',
    'Unnamed: 8':'Percentual de mulheres com peso adequado',
    'Unnamed: 9':'Quantidade de mulheres com sobrepeso',
    'Unnamed: 10':'Percentual de mulheres com sobrepeso',
    'Unnamed: 11':'Quantidade de mulheres com obesidade grau I',
    'Unnamed: 12':'Percentual de mulheres com obesidade grau I',
    'Unnamed: 13':'Quantidade de mulheres com obesidade grau II',
    'Unnamed: 14':'Percentual de mulheres com obesidade grau II',
    'Unnamed: 15':'Quantidade de mulheres com obesidade grau III',
    'Unnamed: 16':'Percentual de mulheres com obesidade grau III',
    'Unnamed: 17':'Quantidade total de mulheres'
                                                                            })
df_fem_2020_renomeado = pd.DataFrame.rename(df_fem_2020_col_sel, columns = {
    'Total':'Quantidade de mulheres com baixo peso',
    'Unnamed: 6': 'Percentual de mulheres baixo peso',
    'Unnamed: 7':'Quantidade de mulheres com peso adequado',
    'Unnamed: 8':'Percentual de mulheres com peso adequado',
    'Unnamed: 9':'Quantidade de mulheres com sobrepeso',
    'Unnamed: 10':'Percentual de mulheres com sobrepeso',
    'Unnamed: 11':'Quantidade de mulheres com obesidade grau I',
    'Unnamed: 12':'Percentual de mulheres com obesidade grau I',
    'Unnamed: 13':'Quantidade de mulheres com obesidade grau II',
    'Unnamed: 14':'Percentual de mulheres com obesidade grau II',
    'Unnamed: 15':'Quantidade de mulheres com obesidade grau III',
    'Unnamed: 16':'Percentual de mulheres com obesidade grau III',
    'Unnamed: 17':'Quantidade total de mulheres'
                                                                            })
df_fem_2021_renomeado = pd.DataFrame.rename(df_fem_2021_col_sel, columns = {
    'Total':'Quantidade de mulheres com baixo peso',
    'Unnamed: 6': 'Percentual de mulheres baixo peso',
    'Unnamed: 7':'Quantidade de mulheres com peso adequado',
    'Unnamed: 8':'Percentual de mulheres com peso adequado',
    'Unnamed: 9':'Quantidade de mulheres com sobrepeso',
    'Unnamed: 10':'Percentual de mulheres com sobrepeso',
    'Unnamed: 11':'Quantidade de mulheres com obesidade grau I',
    'Unnamed: 12':'Percentual de mulheres com obesidade grau I',
    'Unnamed: 13':'Quantidade de mulheres com obesidade grau II',
    'Unnamed: 14':'Percentual de mulheres com obesidade grau II',
    'Unnamed: 15':'Quantidade de mulheres com obesidade grau III',
    'Unnamed: 16':'Percentual de mulheres com obesidade grau III',
    'Unnamed: 17':'Quantidade total de mulheres'
                                                                            })
df_fem_2022_renomeado = pd.DataFrame.rename(df_fem_2022_col_sel, columns = {
    'Total':'Quantidade de mulheres com baixo peso',
    'Unnamed: 6': 'Percentual de mulheres baixo peso',
    'Unnamed: 7':'Quantidade de mulheres com peso adequado',
    'Unnamed: 8':'Percentual de mulheres com peso adequado',
    'Unnamed: 9':'Quantidade de mulheres com sobrepeso',
    'Unnamed: 10':'Percentual de mulheres com sobrepeso',
    'Unnamed: 11':'Quantidade de mulheres com obesidade grau I',
    'Unnamed: 12':'Percentual de mulheres com obesidade grau I',
    'Unnamed: 13':'Quantidade de mulheres com obesidade grau II',
    'Unnamed: 14':'Percentual de mulheres com obesidade grau II',
    'Unnamed: 15':'Quantidade de mulheres com obesidade grau III',
    'Unnamed: 16':'Percentual de mulheres com obesidade grau III',
    'Unnamed: 17':'Quantidade total de mulheres'
                                                                            })
df_fem_2023_renomeado = pd.DataFrame.rename(df_fem_2023_col_sel, columns = {
    'Total':'Quantidade de mulheres com baixo peso',
    'Unnamed: 6': 'Percentual de mulheres baixo peso',
    'Unnamed: 7':'Quantidade de mulheres com peso adequado',
    'Unnamed: 8':'Percentual de mulheres com peso adequado',
    'Unnamed: 9':'Quantidade de mulheres com sobrepeso',
    'Unnamed: 10':'Percentual de mulheres com sobrepeso',
    'Unnamed: 11':'Quantidade de mulheres com obesidade grau I',
    'Unnamed: 12':'Percentual de mulheres com obesidade grau I',
    'Unnamed: 13':'Quantidade de mulheres com obesidade grau II',
    'Unnamed: 14':'Percentual de mulheres com obesidade grau II',
    'Unnamed: 15':'Quantidade de mulheres com obesidade grau III',
    'Unnamed: 16':'Percentual de mulheres com obesidade grau III',
    'Unnamed: 17':'Quantidade total de mulheres'
                                                                            })
df_fem_2024_renomeado = pd.DataFrame.rename(df_fem_2024_col_sel, columns = {
    'Total':'Quantidade de mulheres com baixo peso',
    'Unnamed: 6': 'Percentual de mulheres baixo peso',
    'Unnamed: 7':'Quantidade de mulheres com peso adequado',
    'Unnamed: 8':'Percentual de mulheres com peso adequado',
    'Unnamed: 9':'Quantidade de mulheres com sobrepeso',
    'Unnamed: 10':'Percentual de mulheres com sobrepeso',
    'Unnamed: 11':'Quantidade de mulheres com obesidade grau I',
    'Unnamed: 12':'Percentual de mulheres com obesidade grau I',
    'Unnamed: 13':'Quantidade de mulheres com obesidade grau II',
    'Unnamed: 14':'Percentual de mulheres com obesidade grau II',
    'Unnamed: 15':'Quantidade de mulheres com obesidade grau III',
    'Unnamed: 16':'Percentual de mulheres com obesidade grau III',
    'Unnamed: 17':'Quantidade total de mulheres'
                                                                            })
df_fem_2025_renomeado = pd.DataFrame.rename(df_fem_2025_col_sel, columns = {
    'Total':'Quantidade de mulheres com baixo peso',
    'Unnamed: 6': 'Percentual de mulheres baixo peso',
    'Unnamed: 7':'Quantidade de mulheres com peso adequado',
    'Unnamed: 8':'Percentual de mulheres com peso adequado',
    'Unnamed: 9':'Quantidade de mulheres com sobrepeso',
    'Unnamed: 10':'Percentual de mulheres com sobrepeso',
    'Unnamed: 11':'Quantidade de mulheres com obesidade grau I',
    'Unnamed: 12':'Percentual de mulheres com obesidade grau I',
    'Unnamed: 13':'Quantidade de mulheres com obesidade grau II',
    'Unnamed: 14':'Percentual de mulheres com obesidade grau II',
    'Unnamed: 15':'Quantidade de mulheres com obesidade grau III',
    'Unnamed: 16':'Percentual de mulheres com obesidade grau III',
    'Unnamed: 17':'Quantidade total de mulheres'
                                                                            })
df_fem_2008_renomeado

,Ano,Código da Região de Saúde,Região de Saúde,Quantidade de mulheres com baixo peso,Percentual de mulheres baixo peso,Quantidade de mulheres com peso adequado,Percentual de mulheres com peso adequado,Quantidade de mulheres com sobrepeso,Percentual de mulheres com sobrepeso,Quantidade de mulheres com obesidade grau I,Percentual de mulheres com obesidade grau I,Quantidade de mulheres com obesidade grau II,Percentual de mulheres com obesidade grau II,Quantidade de mulheres com obesidade grau III,Percentual de mulheres com obesidade grau III,Quantidade total de mulheres
0,2008,2,2ª Região de Saúde,468,4.59%,5005,49.04%,2953,28.94%,1264,12.39%,370,3.63%,145,1.42%,10205
1,2008,44,1ª Região de Saúde,557,4.97%,5306,47.38%,3513,31.37%,1310,11.7%,372,3.32%,141,1.26%,11199
2,2008,45,7ª Região de Saúde,2623,8.28%,15266,48.18%,10170,32.1%,2702,8.53%,673,2.12%,249,0.79%,31683
3,2008,46,9ª Região de Saúde,1567,7.4%,11475,54.16%,5765,27.21%,1788,8.44%,455,2.15%,138,0.65%,21188
4,2008,169,3ª Região de Saúde,2005,10.66%,9507,50.52%,4965,26.39%,1771,9.41%,425,2.26%,144,0.77%,18817
5,2008,226,10ª Região de Saúde,824,6.55%,6963,55.32%,3430,27.25%,1010,8.02%,254,2.02%,105,0.83%,12586
6,2008,393,4ª Região de Saúde,508,4.59%,6538,59.03%,2983,26.93%,799,7.21%,166,1.5%,82,0.74%,11076
7,2008,394,5ª Região de Saúde,1735,13.21%,5690,43.34%,3599,27.41%,1508,11.49%,443,3.37%,155,1.18%,13130
8,2008,395,6ª Região de Saúde,648,5.43%,5876,49.25%,3537,29.65%,1319,11.06%,391,3.28%,159,1.33%,11930
9,2008,396,8ª Região de Saúde,830,6.98%,6035,50.74%,3480,29.26%,1130,9.5%,310,2.61%,109,0.92%,11894
10,2008,AL,AL,11765,7.65%,77661,50.53%,44395,28.88%,14601,9.5%,3859,2.51%,1427,0.93%,153708
11,2008,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,173447,6.44%,1463592,54.36%,744100,27.64%,232553,8.64%,57978,2.15%,20666,0.77%,2692336
12,2008,TOTAL BRASIL,TOTAL BRASIL,298609,5.78%,2655970,51.43%,1462587,28.32%,526146,10.19%,156355,3.03%,64856,1.26%,5164523

Juntando as informações num dataframe só:

A nova variável usa o concatenar (juntar) para organizar todas as informações.

- pd.concat() -  empilha verticalmente e une todas as tabelas criadas numa só.

-  ignore_index=True - o pandas descarta os índices originais de cada DataFrame e cria um novo índice numérico sequencial que será organizado de 2008 até 2025.

In [15]:
df_concatenado_fem = pd.concat([
        df_fem_2008_renomeado,
        df_fem_2009_renomeado,
        df_fem_2010_renomeado,
        df_fem_2011_renomeado,
        df_fem_2012_renomeado,
        df_fem_2013_renomeado,
        df_fem_2014_renomeado,
        df_fem_2015_renomeado,
        df_fem_2016_renomeado,
        df_fem_2017_renomeado,
        df_fem_2018_renomeado,
        df_fem_2019_renomeado,
        df_fem_2020_renomeado,
        df_fem_2021_renomeado,
        df_fem_2022_renomeado,
        df_fem_2023_renomeado,
        df_fem_2024_renomeado,
        df_fem_2025_renomeado,]
  ,ignore_index=True
)
df_concatenado_fem

,Ano,Código da Região de Saúde,Região de Saúde,Quantidade de mulheres com baixo peso,Percentual de mulheres baixo peso,Quantidade de mulheres com peso adequado,Percentual de mulheres com peso adequado,Quantidade de mulheres com sobrepeso,Percentual de mulheres com sobrepeso,Quantidade de mulheres com obesidade grau I,Percentual de mulheres com obesidade grau I,Quantidade de mulheres com obesidade grau II,Percentual de mulheres com obesidade grau II,Quantidade de mulheres com obesidade grau III,Percentual de mulheres com obesidade grau III,Quantidade total de mulheres
0,2008,2,2ª Região de Saúde,468,4.59%,5005,49.04%,2953,28.94%,1264,12.39%,370,3.63%,145,1.42%,10205
1,2008,44,1ª Região de Saúde,557,4.97%,5306,47.38%,3513,31.37%,1310,11.7%,372,3.32%,141,1.26%,11199
2,2008,45,7ª Região de Saúde,2623,8.28%,15266,48.18%,10170,32.1%,2702,8.53%,673,2.12%,249,0.79%,31683
3,2008,46,9ª Região de Saúde,1567,7.4%,11475,54.16%,5765,27.21%,1788,8.44%,455,2.15%,138,0.65%,21188
4,2008,169,3ª Região de Saúde,2005,10.66%,9507,50.52%,4965,26.39%,1771,9.41%,425,2.26%,144,0.77%,18817
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,2025,395,6ª Região de Saúde,694,1.85%,8016,21.31%,12059,32.06%,9783,26.01%,4564,12.13%,2499,6.64%,37615
230,2025,396,8ª Região de Saúde,539,2.25%,6187,25.77%,8306,34.6%,5562,23.17%,2281,9.5%,1129,4.7%,24004
231,2025,AL,AL,9515,2%,113897,24%,158167,33.33%,115598,24.36%,51288,10.81%,26141,5.51%,474606
232,2025,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,142992,1.96%,1923043,26.41%,2571337,35.31%,1660315,22.8%,668429,9.18%,315540,4.33%,7281656
233,2025,TOTAL BRASIL,TOTAL BRASIL,396796,1.78%,5676428,25.47%,7509377,33.69%,5140233,23.06%,2293482,10.29%,1271334,5.7%,22287650

In [16]:
df_concatenado_mas = pd.concat([
        df_mas_2008_renomeado,
        df_mas_2009_renomeado,
        df_mas_2010_renomeado,
        df_mas_2011_renomeado,
        df_mas_2012_renomeado,
        df_mas_2013_renomeado,
        df_mas_2014_renomeado,
        df_mas_2015_renomeado,
        df_mas_2016_renomeado,
        df_mas_2017_renomeado,
        df_mas_2018_renomeado,
        df_mas_2019_renomeado,
        df_mas_2020_renomeado,
        df_mas_2021_renomeado,
        df_mas_2022_renomeado,
        df_mas_2023_renomeado,
        df_mas_2024_renomeado,
        df_mas_2025_renomeado,]
  ,ignore_index=True
)
df_concatenado_mas

,Ano,Código da Região de Saúde,Região de Saúde,Quantidade de homens com baixo peso,Percentual de homens baixo peso,Quantidade de homens com peso adequado,Percentual de homens com peso adequado,Quantidade de homens com sobrepeso,Percentual de homens com sobrepeso,Quantidade de homens com obesidade grau I,Percentual de homens com obesidade grau I,Quantidade de homens com obesidade grau II,Percentual de homens com obesidade grau II,Quantidade de homens com obesidade grau III,Percentual de homens com obesidade grau III,Quantidade total de homens
0,2008,2,2ª Região de Saúde,0,-,2,40%,2,40%,1,20%,0,-,0,-,5
1,2008,44,1ª Região de Saúde,0,-,15,53.57%,5,17.86%,5,17.86%,3,10.71%,0,-,28
2,2008,45,7ª Região de Saúde,5,4.2%,65,54.62%,31,26.05%,15,12.61%,3,2.52%,0,-,119
3,2008,46,9ª Região de Saúde,10,3.26%,179,58.31%,97,31.6%,15,4.89%,3,0.98%,3,0.98%,307
4,2008,169,3ª Região de Saúde,3,17.65%,10,58.82%,1,5.88%,3,17.65%,0,-,0,-,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,2025,395,6ª Região de Saúde,200,1.33%,4398,29.14%,5641,37.38%,3333,22.09%,1081,7.16%,438,2.9%,15091
230,2025,396,8ª Região de Saúde,164,1.98%,2795,33.72%,3105,37.45%,1618,19.52%,443,5.34%,165,1.99%,8290
231,2025,AL,AL,3491,2%,54926,31.47%,64903,37.19%,35689,20.45%,10861,6.22%,4644,2.66%,174514
232,2025,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,50178,2.12%,818473,34.51%,894273,37.71%,434981,18.34%,123231,5.2%,50444,2.13%,2371580
233,2025,TOTAL BRASIL,TOTAL BRASIL,179875,1.91%,2991194,31.84%,3475520,37%,1869507,19.9%,598061,6.37%,280109,2.98%,9394266

Juntando os concatenados

Em vista que conseguimos criar as tabelas no período de 2008 a 2025 para os segmentos masculinos e femininos é necessário uní-las

- pd.merge() - concatena apenas duas tabelas que detenham as mesmas colunas, isto é, exatamente os DataFrames anteriores.

In [17]:
df_concatenado = pd.merge(df_concatenado_fem, df_concatenado_mas)
df_concatenado

,Ano,Código da Região de Saúde,Região de Saúde,Quantidade de mulheres com baixo peso,Percentual de mulheres baixo peso,Quantidade de mulheres com peso adequado,Percentual de mulheres com peso adequado,Quantidade de mulheres com sobrepeso,Percentual de mulheres com sobrepeso,Quantidade de mulheres com obesidade grau I,...,Percentual de homens com peso adequado,Quantidade de homens com sobrepeso,Percentual de homens com sobrepeso,Quantidade de homens com obesidade grau I,Percentual de homens com obesidade grau I,Quantidade de homens com obesidade grau II,Percentual de homens com obesidade grau II,Quantidade de homens com obesidade grau III,Percentual de homens com obesidade grau III,Quantidade total de homens
0,2008,2,2ª Região de Saúde,468,4.59%,5005,49.04%,2953,28.94%,1264,...,40%,2,40%,1,20%,0,-,0,-,5
1,2008,44,1ª Região de Saúde,557,4.97%,5306,47.38%,3513,31.37%,1310,...,53.57%,5,17.86%,5,17.86%,3,10.71%,0,-,28
2,2008,45,7ª Região de Saúde,2623,8.28%,15266,48.18%,10170,32.1%,2702,...,54.62%,31,26.05%,15,12.61%,3,2.52%,0,-,119
3,2008,46,9ª Região de Saúde,1567,7.4%,11475,54.16%,5765,27.21%,1788,...,58.31%,97,31.6%,15,4.89%,3,0.98%,3,0.98%,307
4,2008,169,3ª Região de Saúde,2005,10.66%,9507,50.52%,4965,26.39%,1771,...,58.82%,1,5.88%,3,17.65%,0,-,0,-,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,2025,395,6ª Região de Saúde,694,1.85%,8016,21.31%,12059,32.06%,9783,...,29.14%,5641,37.38%,3333,22.09%,1081,7.16%,438,2.9%,15091
230,2025,396,8ª Região de Saúde,539,2.25%,6187,25.77%,8306,34.6%,5562,...,33.72%,3105,37.45%,1618,19.52%,443,5.34%,165,1.99%,8290
231,2025,AL,AL,9515,2%,113897,24%,158167,33.33%,115598,...,31.47%,64903,37.19%,35689,20.45%,10861,6.22%,4644,2.66%,174514
232,2025,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,142992,1.96%,1923043,26.41%,2571337,35.31%,1660315,...,34.51%,894273,37.71%,434981,18.34%,123231,5.2%,50444,2.13%,2371580
233,2025,TOTAL BRASIL,TOTAL BRASIL,396796,1.78%,5676428,25.47%,7509377,33.69%,5140233,...,31.84%,3475520,37%,1869507,19.9%,598061,6.37%,280109,2.98%,9394266

Trocando '-' por 0:

- .replace('-', 0) - Substitui valores nos DataFrames, pois em todos os caractere '-' será modificado por 0 (zero).

In [18]:
df_concatenado_1 = df_concatenado.replace('-', 0)
df_concatenado_1

,Ano,Código da Região de Saúde,Região de Saúde,Quantidade de mulheres com baixo peso,Percentual de mulheres baixo peso,Quantidade de mulheres com peso adequado,Percentual de mulheres com peso adequado,Quantidade de mulheres com sobrepeso,Percentual de mulheres com sobrepeso,Quantidade de mulheres com obesidade grau I,...,Percentual de homens com peso adequado,Quantidade de homens com sobrepeso,Percentual de homens com sobrepeso,Quantidade de homens com obesidade grau I,Percentual de homens com obesidade grau I,Quantidade de homens com obesidade grau II,Percentual de homens com obesidade grau II,Quantidade de homens com obesidade grau III,Percentual de homens com obesidade grau III,Quantidade total de homens
0,2008,2,2ª Região de Saúde,468,4.59%,5005,49.04%,2953,28.94%,1264,...,40%,2,40%,1,20%,0,0,0,0,5
1,2008,44,1ª Região de Saúde,557,4.97%,5306,47.38%,3513,31.37%,1310,...,53.57%,5,17.86%,5,17.86%,3,10.71%,0,0,28
2,2008,45,7ª Região de Saúde,2623,8.28%,15266,48.18%,10170,32.1%,2702,...,54.62%,31,26.05%,15,12.61%,3,2.52%,0,0,119
3,2008,46,9ª Região de Saúde,1567,7.4%,11475,54.16%,5765,27.21%,1788,...,58.31%,97,31.6%,15,4.89%,3,0.98%,3,0.98%,307
4,2008,169,3ª Região de Saúde,2005,10.66%,9507,50.52%,4965,26.39%,1771,...,58.82%,1,5.88%,3,17.65%,0,0,0,0,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,2025,395,6ª Região de Saúde,694,1.85%,8016,21.31%,12059,32.06%,9783,...,29.14%,5641,37.38%,3333,22.09%,1081,7.16%,438,2.9%,15091
230,2025,396,8ª Região de Saúde,539,2.25%,6187,25.77%,8306,34.6%,5562,...,33.72%,3105,37.45%,1618,19.52%,443,5.34%,165,1.99%,8290
231,2025,AL,AL,9515,2%,113897,24%,158167,33.33%,115598,...,31.47%,64903,37.19%,35689,20.45%,10861,6.22%,4644,2.66%,174514
232,2025,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,142992,1.96%,1923043,26.41%,2571337,35.31%,1660315,...,34.51%,894273,37.71%,434981,18.34%,123231,5.2%,50444,2.13%,2371580
233,2025,TOTAL BRASIL,TOTAL BRASIL,396796,1.78%,5676428,25.47%,7509377,33.69%,5140233,...,31.84%,3475520,37%,1869507,19.9%,598061,6.37%,280109,2.98%,9394266

Vendo as colunas:

- .columns - retorna um Index contendo os nomes de todas as colunas da tabela selecionada.

In [19]:
df_concatenado_1.columns

Index(['Ano', 'Código da Região de Saúde', 'Região de Saúde',
       'Quantidade de mulheres com baixo peso',
       'Percentual de mulheres baixo peso',
       'Quantidade de mulheres com peso adequado',
       'Percentual de mulheres com peso adequado',
       'Quantidade de mulheres com sobrepeso',
       'Percentual de mulheres com sobrepeso',
       'Quantidade de mulheres com obesidade grau I',
       'Percentual de mulheres com obesidade grau I',
       'Quantidade de mulheres com obesidade grau II',
       'Percentual de mulheres com obesidade grau II',
       'Quantidade de mulheres com obesidade grau III',
       'Percentual de mulheres com obesidade grau III',
       'Quantidade total de mulheres', 'Quantidade de homens com baixo peso',
       'Percentual de homens baixo peso',
       'Quantidade de homens com peso adequado',
       'Percentual de homens com peso adequado',
       'Quantidade de homens com sobrepeso',
       'Percentual de homens com sobrepeso',
       'Quantidade de homens com obesidade grau I',
       'Percentual de homens com obesidade grau I',
       'Quantidade de homens com obesidade grau II',
       'Percentual de homens com obesidade grau II',
       'Quantidade de homens com obesidade grau III',
       'Percentual de homens com obesidade grau III',
       'Quantidade total de homens'],
      dtype='object')

Selecionando as colunas a serem utilizadas:


Atráves da estrutura
- pd.DataFrame ()

Selecionados a tabela e depois quais colunas específicas queremos na nova tabela

-  ,columns = [...]

In [20]:
df_concatenado_col_sel = pd.DataFrame(df_concatenado_1, columns=[
    'Ano',
    'Código da Região de Saúde',
    'Região de Saúde',
    'Quantidade de mulheres com baixo peso',
    'Quantidade de mulheres com peso adequado',
    'Quantidade de mulheres com sobrepeso',
    'Quantidade de mulheres com obesidade grau I',
    'Quantidade de mulheres com obesidade grau II',
    'Quantidade de mulheres com obesidade grau III',
    'Quantidade total de mulheres',
    'Quantidade de homens com baixo peso',
    'Quantidade de homens com peso adequado',
    'Quantidade de homens com sobrepeso',
    'Quantidade de homens com obesidade grau I',
    'Quantidade de homens com obesidade grau II',
    'Quantidade de homens com obesidade grau III',
    'Quantidade total de homens',
])
df_concatenado_col_sel

,Ano,Código da Região de Saúde,Região de Saúde,Quantidade de mulheres com baixo peso,Quantidade de mulheres com peso adequado,Quantidade de mulheres com sobrepeso,Quantidade de mulheres com obesidade grau I,Quantidade de mulheres com obesidade grau II,Quantidade de mulheres com obesidade grau III,Quantidade total de mulheres,Quantidade de homens com baixo peso,Quantidade de homens com peso adequado,Quantidade de homens com sobrepeso,Quantidade de homens com obesidade grau I,Quantidade de homens com obesidade grau II,Quantidade de homens com obesidade grau III,Quantidade total de homens
0,2008,2,2ª Região de Saúde,468,5005,2953,1264,370,145,10205,0,2,2,1,0,0,5
1,2008,44,1ª Região de Saúde,557,5306,3513,1310,372,141,11199,0,15,5,5,3,0,28
2,2008,45,7ª Região de Saúde,2623,15266,10170,2702,673,249,31683,5,65,31,15,3,0,119
3,2008,46,9ª Região de Saúde,1567,11475,5765,1788,455,138,21188,10,179,97,15,3,3,307
4,2008,169,3ª Região de Saúde,2005,9507,4965,1771,425,144,18817,3,10,1,3,0,0,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,2025,395,6ª Região de Saúde,694,8016,12059,9783,4564,2499,37615,200,4398,5641,3333,1081,438,15091
230,2025,396,8ª Região de Saúde,539,6187,8306,5562,2281,1129,24004,164,2795,3105,1618,443,165,8290
231,2025,AL,AL,9515,113897,158167,115598,51288,26141,474606,3491,54926,64903,35689,10861,4644,174514
232,2025,TOTAL REGIÃO NORDESTE,TOTAL REGIÃO NORDESTE,142992,1923043,2571337,1660315,668429,315540,7281656,50178,818473,894273,434981,123231,50444,2371580
233,2025,TOTAL BRASIL,TOTAL BRASIL,396796,5676428,7509377,5140233,2293482,1271334,22287650,179875,2991194,3475520,1869507,598061,280109,9394266

Verificando a natureza dos dados:

.dtypes - retorna o tipo de dados de cada coluna da tabela.

In [21]:
print(df_concatenado_col_sel.dtypes)

Ano                                               int64
Código da Região de Saúde                        object
Região de Saúde                                  object
Quantidade de mulheres com baixo peso             int64
Quantidade de mulheres com peso adequado          int64
Quantidade de mulheres com sobrepeso              int64
Quantidade de mulheres com obesidade grau I       int64
Quantidade de mulheres com obesidade grau II      int64
Quantidade de mulheres com obesidade grau III     int64
Quantidade total de mulheres                      int64
Quantidade de homens com baixo peso               int64
Quantidade de homens com peso adequado            int64
Quantidade de homens com sobrepeso                int64
Quantidade de homens com obesidade grau I         int64
Quantidade de homens com obesidade grau II        int64
Quantidade de homens com obesidade grau III       int64
Quantidade total de homens                        int64
dtype: object

Transformando as colunas:

Compreendendo que existem colunas com o tipo objetivo, mas manipulamos números (int64)


- Na tabela específica abrimos [] da coluna com formato de objeto
- = atribui que pd.to_numeric que força a transformação da coluna para número da tabela
- ,errors='coerce' é o parâmetro de segurança, portanto caso hajaalgum valor impossível de converter tal valor retorna NaN (Not a Number).

Obs. Nessa etapa houve substituição das informações da tabela anterior (que é a tabela quase final do trabalho)

In [22]:
df_concatenado_col_sel['Quantidade de mulheres com peso adequado'] = pd.to_numeric(df_concatenado_col_sel['Quantidade de mulheres com peso adequado'], errors='coerce')
df_concatenado_col_sel['Quantidade de mulheres com sobrepeso'] =  pd.to_numeric(df_concatenado_col_sel['Quantidade de mulheres com sobrepeso'], errors='coerce')
df_concatenado_col_sel['Quantidade de mulheres com obesidade grau I'] =  pd.to_numeric(df_concatenado_col_sel['Quantidade de mulheres com obesidade grau I'], errors='coerce')
df_concatenado_col_sel['Quantidade de mulheres com obesidade grau II'] =  pd.to_numeric(df_concatenado_col_sel['Quantidade de mulheres com obesidade grau II'], errors='coerce')
df_concatenado_col_sel['Quantidade de mulheres com obesidade grau III'] =    pd.to_numeric(df_concatenado_col_sel['Quantidade de mulheres com obesidade grau III'], errors='coerce')
df_concatenado_col_sel['Quantidade total de mulheres'] =  pd.to_numeric(df_concatenado_col_sel['Quantidade total de mulheres'], errors='coerce')
df_concatenado_col_sel['Quantidade de homens com peso adequado'] = pd.to_numeric(df_concatenado_col_sel['Quantidade de homens com peso adequado'], errors='coerce')
df_concatenado_col_sel['Quantidade de homens com sobrepeso'] =  pd.to_numeric(df_concatenado_col_sel['Quantidade de homens com sobrepeso'], errors='coerce')
df_concatenado_col_sel['Quantidade de homens com obesidade grau I'] = pd.to_numeric(df_concatenado_col_sel['Quantidade de homens com obesidade grau I'], errors='coerce')
df_concatenado_col_sel['Quantidade total de homens'] =  pd.to_numeric(df_concatenado_col_sel['Quantidade total de homens'], errors='coerce')
df_concatenado_col_sel.dtypes

Ano                                               int64
Código da Região de Saúde                        object
Região de Saúde                                  object
Quantidade de mulheres com baixo peso             int64
Quantidade de mulheres com peso adequado          int64
Quantidade de mulheres com sobrepeso              int64
Quantidade de mulheres com obesidade grau I       int64
Quantidade de mulheres com obesidade grau II      int64
Quantidade de mulheres com obesidade grau III     int64
Quantidade total de mulheres                      int64
Quantidade de homens com baixo peso               int64
Quantidade de homens com peso adequado            int64
Quantidade de homens com sobrepeso                int64
Quantidade de homens com obesidade grau I         int64
Quantidade de homens com obesidade grau II        int64
Quantidade de homens com obesidade grau III       int64
Quantidade total de homens                        int64
dtype: object

Tabela/DataFrame filtrado pelo total das colunas para 'AL'

Realizando a extração da informação a ser utilizada:

Todas as transformações das tabelas, buscam apenas um objetivo; o total das colunas para o Estado (AL).

Filtrando informações:
-  Novo DataFrame = tabela ['coluna específica'] == atibuto 'AL" na coluna de 'Códido da Região'
&
como formato de confirmação buscamos mais uma coluna['...'] com o mesmo atributo

In [23]:
df_filtrado = df_concatenado_col_sel[
    (df_concatenado_col_sel['Código da Região de Saúde'] == 'AL') &
    (df_concatenado_col_sel['Região de Saúde'] == 'AL')
]
df_filtrado

,Ano,Código da Região de Saúde,Região de Saúde,Quantidade de mulheres com baixo peso,Quantidade de mulheres com peso adequado,Quantidade de mulheres com sobrepeso,Quantidade de mulheres com obesidade grau I,Quantidade de mulheres com obesidade grau II,Quantidade de mulheres com obesidade grau III,Quantidade total de mulheres,Quantidade de homens com baixo peso,Quantidade de homens com peso adequado,Quantidade de homens com sobrepeso,Quantidade de homens com obesidade grau I,Quantidade de homens com obesidade grau II,Quantidade de homens com obesidade grau III,Quantidade total de homens
10,2008,AL,AL,11765,77661,44395,14601,3859,1427,153708,30,527,235,67,11,3,873
23,2009,AL,AL,6604,78270,45383,15316,4233,1455,151261,88,1555,769,218,42,18,2690
36,2010,AL,AL,6457,79859,49036,17102,4540,1752,158746,23,396,234,59,13,8,733
49,2011,AL,AL,6144,80235,51166,19538,5539,2118,164740,44,1183,652,174,45,13,2111
62,2012,AL,AL,6980,94135,69065,29641,8540,3108,211469,60,1108,832,225,67,26,2318
75,2013,AL,AL,8640,108668,83563,37066,10987,4083,253007,51,508,373,134,32,9,1107
88,2014,AL,AL,7932,100725,83980,38977,12035,4507,248156,14,225,187,87,26,8,547
101,2015,AL,AL,7288,102821,92917,45091,14672,5470,268259,201,4013,4172,1830,475,173,10864
114,2016,AL,AL,8469,112249,100748,50120,16845,6561,294992,547,9094,9487,4217,1107,365,24817
127,2017,AL,AL,7899,111260,106390,54184,18844,7205,305782,477,8366,8757,4102,1082,371,23155
140,2018,AL,AL,8165,109971,112732,61147,21748,8549,322312,483,9419,9708,4534,1238,452,25834
153,2019,AL,AL,7152,82426,85766,49387,17817,7408,249956,559,11049,10888,5018,1358,499,29371
166,2020,AL,AL,4405,54987,61956,37988,14534,6294,180164,837,15954,16518,7712,2159,853,44033
179,2021,AL,AL,5707,67668,79000,50184,19745,9478,231782,1150,20257,22285,11039,3344,1658,59733
192,2022,AL,AL,8031,93478,110149,71223,28729,13370,324980,2114,33662,36017,17932,5156,2060,96941
205,2023,AL,AL,8358,95392,119901,81785,34311,16758,356505,2414,38613,42183,21933,6408,2675,114226
218,2024,AL,AL,8709,98448,126823,89382,39020,19350,381732,2569,39000,44410,23973,7017,2883,119852
231,2025,AL,AL,9515,113897,158167,115598,51288,26141,474606,3491,54926,64903,35689,10861,4644,174514

Selecionando as colunas a serem utilizadas:

O DataFrame anterior buscou informações dos totais em cada linha gerando a tabela pré-final.

Basicamente ocultando duas colunas que não fazem mais sentido de aparecerem na tabela

In [24]:
df_filtrado_col_sel = pd.DataFrame(df_filtrado, columns=[
    'Ano',
    'Quantidade de mulheres com baixo peso',
    'Quantidade de mulheres com peso adequado',
    'Quantidade de mulheres com sobrepeso',
    'Quantidade de mulheres com obesidade grau I',
    'Quantidade de mulheres com obesidade grau II',
    'Quantidade de mulheres com obesidade grau III',
    'Quantidade total de mulheres',
    'Quantidade de homens com baixo peso',
    'Quantidade de homens com peso adequado',
    'Quantidade de homens com sobrepeso',
    'Quantidade de homens com obesidade grau I',
    'Quantidade de homens com obesidade grau II',
    'Quantidade de homens com obesidade grau III',
    'Quantidade total de homens'
])
df_filtrado_col_sel

,Ano,Quantidade de mulheres com baixo peso,Quantidade de mulheres com peso adequado,Quantidade de mulheres com sobrepeso,Quantidade de mulheres com obesidade grau I,Quantidade de mulheres com obesidade grau II,Quantidade de mulheres com obesidade grau III,Quantidade total de mulheres,Quantidade de homens com baixo peso,Quantidade de homens com peso adequado,Quantidade de homens com sobrepeso,Quantidade de homens com obesidade grau I,Quantidade de homens com obesidade grau II,Quantidade de homens com obesidade grau III,Quantidade total de homens
10,2008,11765,77661,44395,14601,3859,1427,153708,30,527,235,67,11,3,873
23,2009,6604,78270,45383,15316,4233,1455,151261,88,1555,769,218,42,18,2690
36,2010,6457,79859,49036,17102,4540,1752,158746,23,396,234,59,13,8,733
49,2011,6144,80235,51166,19538,5539,2118,164740,44,1183,652,174,45,13,2111
62,2012,6980,94135,69065,29641,8540,3108,211469,60,1108,832,225,67,26,2318
75,2013,8640,108668,83563,37066,10987,4083,253007,51,508,373,134,32,9,1107
88,2014,7932,100725,83980,38977,12035,4507,248156,14,225,187,87,26,8,547
101,2015,7288,102821,92917,45091,14672,5470,268259,201,4013,4172,1830,475,173,10864
114,2016,8469,112249,100748,50120,16845,6561,294992,547,9094,9487,4217,1107,365,24817
127,2017,7899,111260,106390,54184,18844,7205,305782,477,8366,8757,4102,1082,371,23155
140,2018,8165,109971,112732,61147,21748,8549,322312,483,9419,9708,4534,1238,452,25834
153,2019,7152,82426,85766,49387,17817,7408,249956,559,11049,10888,5018,1358,499,29371
166,2020,4405,54987,61956,37988,14534,6294,180164,837,15954,16518,7712,2159,853,44033
179,2021,5707,67668,79000,50184,19745,9478,231782,1150,20257,22285,11039,3344,1658,59733
192,2022,8031,93478,110149,71223,28729,13370,324980,2114,33662,36017,17932,5156,2060,96941
205,2023,8358,95392,119901,81785,34311,16758,356505,2414,38613,42183,21933,6408,2675,114226
218,2024,8709,98448,126823,89382,39020,19350,381732,2569,39000,44410,23973,7017,2883,119852
231,2025,9515,113897,158167,115598,51288,26141,474606,3491,54926,64903,35689,10861,4644,174514

Resetando o indice:

* Tabela Final.

Substituindo informações na antiga tabela
*df_filtrado_col_set

- = tabela.index_reset() - Reseta o índice da tabela anterior que retirava de linhas longíquas as informações que estavam agrupadas e gera um índice novo do 0 (zero).

- drop=True: o índice antigo é descartado.

In [25]:
df_filtrado_col_sel = df_filtrado_col_sel.reset_index(drop=True)
df_filtrado_col_sel

,Ano,Quantidade de mulheres com baixo peso,Quantidade de mulheres com peso adequado,Quantidade de mulheres com sobrepeso,Quantidade de mulheres com obesidade grau I,Quantidade de mulheres com obesidade grau II,Quantidade de mulheres com obesidade grau III,Quantidade total de mulheres,Quantidade de homens com baixo peso,Quantidade de homens com peso adequado,Quantidade de homens com sobrepeso,Quantidade de homens com obesidade grau I,Quantidade de homens com obesidade grau II,Quantidade de homens com obesidade grau III,Quantidade total de homens
0,2008,11765,77661,44395,14601,3859,1427,153708,30,527,235,67,11,3,873
1,2009,6604,78270,45383,15316,4233,1455,151261,88,1555,769,218,42,18,2690
2,2010,6457,79859,49036,17102,4540,1752,158746,23,396,234,59,13,8,733
3,2011,6144,80235,51166,19538,5539,2118,164740,44,1183,652,174,45,13,2111
4,2012,6980,94135,69065,29641,8540,3108,211469,60,1108,832,225,67,26,2318
5,2013,8640,108668,83563,37066,10987,4083,253007,51,508,373,134,32,9,1107
6,2014,7932,100725,83980,38977,12035,4507,248156,14,225,187,87,26,8,547
7,2015,7288,102821,92917,45091,14672,5470,268259,201,4013,4172,1830,475,173,10864
8,2016,8469,112249,100748,50120,16845,6561,294992,547,9094,9487,4217,1107,365,24817
9,2017,7899,111260,106390,54184,18844,7205,305782,477,8366,8757,4102,1082,371,23155
10,2018,8165,109971,112732,61147,21748,8549,322312,483,9419,9708,4534,1238,452,25834
11,2019,7152,82426,85766,49387,17817,7408,249956,559,11049,10888,5018,1358,499,29371
12,2020,4405,54987,61956,37988,14534,6294,180164,837,15954,16518,7712,2159,853,44033
13,2021,5707,67668,79000,50184,19745,9478,231782,1150,20257,22285,11039,3344,1658,59733
14,2022,8031,93478,110149,71223,28729,13370,324980,2114,33662,36017,17932,5156,2060,96941
15,2023,8358,95392,119901,81785,34311,16758,356505,2414,38613,42183,21933,6408,2675,114226
16,2024,8709,98448,126823,89382,39020,19350,381732,2569,39000,44410,23973,7017,2883,119852
17,2025,9515,113897,158167,115598,51288,26141,474606,3491,54926,64903,35689,10861,4644,174514

Salvando a base de dados a ser utilizada na análise:


- .to_excel() – exportando para Excel

- ,index=False - Não será baixada com o índice numérico

In [26]:
df_filtrado_col_sel.to_excel('GRUPO_3_base_dados.xlsx', index=False)